'use client'
import { useEffect, useState } from 'react'
import Link from 'next/link'
import CoachSidebar from '@/components/CoachSidebar'
import EmptyState from '@/components/EmptyState'
import LoadingState from '@/components/LoadingState'
type AthleteBalance={id:string;name:string;avatar_url?:string|null;charged_cents:number;paid_cents:number;owed_cents:number}
const money=(cents:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(cents/100)
export default function CoachPaymentCenter(){
 const[athletes,setAthletes]=useState<AthleteBalance[]>([]);const[totals,setTotals]=useState({charged_cents:0,paid_cents:0,owed_cents:0});const[loading,setLoading]=useState(true);const[notice,setNotice]=useState('')
 useEffect(()=>{let active=true;fetch('/api/coach/payment-summary',{cache:'no-store'}).then(async r=>({ok:r.ok,p:await r.json().catch(()=>({}))})).then(({ok,p})=>{if(!active)return;if(!ok)setNotice(p.error||'Unable to load payments.');else{setAthletes(p.athletes||[]);setTotals(p.totals||{charged_cents:0,paid_cents:0,owed_cents:0})}setLoading(false)}).catch(()=>{if(active){setNotice('Unable to load payments.');setLoading(false)}});return()=>{active=false}},[])
 return <main className="page-shell"><div className="relative z-10 px-4 py-6 sm:px-6 sm:py-10"><div className="grid gap-6 lg:grid-cols-[220px_minmax(0,1fr)]"><CoachSidebar/><section><p className="text-xs font-semibold uppercase tracking-[.2em] text-neutral-500">Payment center</p><h1 className="mt-1 text-3xl font-bold">Coach payments</h1><p className="mt-2 text-neutral-600">Balances for athletes in your currently selected workspace and team.</p>{notice&&<p className="mt-4 rounded-xl border bg-white p-3 text-sm">{notice}</p>}
 <div className="mt-6 grid gap-3 sm:grid-cols-3">{[['Charged',totals.charged_cents],['Collected',totals.paid_cents],['Outstanding',totals.owed_cents]].map(([label,value])=><div key={String(label)} className="glass-card border bg-white p-5"><p className="text-xs uppercase tracking-[.18em] text-neutral-500">{label}</p><p className="mt-2 text-2xl font-bold">{money(Number(value))}</p></div>)}</div>
 {loading?<LoadingState className="mt-6" label="Loading payments…"/>:athletes.length===0?<EmptyState className="mt-6" title="No athlete balances" description="Charges for athletes in this workspace will appear here."/>:<div className="mt-6 overflow-hidden rounded-2xl border bg-white">{athletes.map(a=><div key={a.id} className="flex flex-wrap items-center gap-4 border-b p-4 last:border-0"><div className="flex h-10 w-10 items-center justify-center overflow-hidden rounded-full bg-neutral-900 text-xs font-bold text-white">{a.avatar_url?<img src={a.avatar_url} alt="" className="h-full w-full object-cover"/>:a.name.split(' ').map(v=>v[0]).slice(0,2).join('')}</div><div className="min-w-40 flex-1"><p className="font-semibold">{a.name}</p><p className="text-sm text-neutral-500">{money(a.paid_cents)} collected</p></div><div className="text-right"><p className="font-semibold">{money(a.owed_cents)}</p><p className="text-xs text-neutral-500">outstanding</p></div></div>)}</div>}
 <div className="mt-6 flex gap-3"><Link href="/coach/revenue" className="rounded-full bg-[#191919] px-5 py-2.5 text-sm font-semibold text-white">Revenue and payouts</Link><Link href="/coach/bookings" className="rounded-full border px-5 py-2.5 text-sm font-semibold">Training payments</Link></div>
 </section></div></div></main>}
