import { supabaseAdmin } from '@/lib/supabaseAdmin'
import { requireWorkspaceContext, workspaceCan } from '@/lib/workspaceAuthority'

export type PortalKind = 'organization'|'coach'|'parent'
export type CapabilityGrant = { view:boolean; manage:boolean; pay:boolean; waive:boolean; refund:boolean }
export type PortalCapabilityDocument = { schema_version:string; portal:PortalKind; workspace_id:string|null; organization_id:string|null; role:string; capabilities:Record<string,CapabilityGrant> }
const grant=(view=true,manage=false,pay=false,waive=false,refund=false):CapabilityGrant=>({view,manage,pay,waive,refund})

export async function resolvePortalCapabilities(userId:string,requestedWorkspaceId?:string|null,requestedOrgId?:string|null):Promise<PortalCapabilityDocument|null>{
  let workspace=await requireWorkspaceContext(userId,requestedWorkspaceId||undefined)
  if(!workspace&&requestedOrgId){const{data:membership}=await supabaseAdmin.from('organization_memberships').select('role').eq('org_id',requestedOrgId).eq('user_id',userId).eq('status','active').maybeSingle();if(membership){const canManage=['owner','admin','org_admin','club_admin','travel_admin','school_admin','athletic_director','program_director','team_manager'].includes(String(membership.role));return organizationDocument(null,requestedOrgId,String(membership.role||'member'),canManage)}}
  if(workspace?.type==='organization'&&workspace.organizationId){const manage=workspaceCan(workspace,'manage_payments');return organizationDocument(workspace.id,workspace.organizationId,workspace.roles[0]||'member',manage)}
  if(workspace?.type==='independent_coach')return coachDocument(workspace.id,workspace.roles[0]||'owner')
  const{data:profile}=await supabaseAdmin.from('profiles').select('role').eq('id',userId).maybeSingle();const role=String(profile?.role||'athlete')
  return role==='coach'?coachDocument(workspace?.id||null,role):parentDocument(workspace?.id||null,role)
}
const common={notifications:grant(),messages:grant(),calendar:grant(),settings:grant(),support:grant(),profile:grant()}
const organizationDocument=(workspaceId:string|null,orgId:string,role:string,manage:boolean):PortalCapabilityDocument=>({schema_version:'2026-08-18',portal:'organization',workspace_id:workspaceId,organization_id:orgId,role,capabilities:{...common,dashboard:grant(),teams:grant(true,manage),coaches:grant(true,manage),contacts:grant(),permissions:grant(true,manage),notes:grant(true,manage),waivers:grant(true,manage),tryouts:grant(true,manage),registrations:grant(true,manage),games:grant(true,manage),seasons:grant(true,manage),marketplace:grant(true,manage,false,false,manage),payments:grant(true,manage,false,manage,manage),dues:grant(true,manage,false,manage,manage),events:grant(true,manage),facilities:grant(true,manage,true,false,manage),fundraising:grant(true,manage),billing:grant(true,manage),reports:grant(),audit:grant(),compliance:grant(true,manage),stripe_connect:grant(true,manage)}})
const coachDocument=(workspaceId:string|null,role:string):PortalCapabilityDocument=>({schema_version:'2026-08-18',portal:'coach',workspace_id:workspaceId,organization_id:null,role,capabilities:{...common,dashboard:grant(),athletes:grant(true,true),bookings:grant(true,true),availability:grant(true,true),notes:grant(true,true),marketplace:grant(true,true,false,false,true),programs:grant(true,true),memberships:grant(true,true),payments:grant(),waivers:grant(true,true),reviews:grant(),reports:grant(),retention:grant(),organizations_teams:grant(),facilities:grant(true,true,true,false,true),stripe_connect:grant(true,true)}})
const parentDocument=(workspaceId:string|null,role:string):PortalCapabilityDocument=>({schema_version:'2026-08-18',portal:'parent',workspace_id:workspaceId,organization_id:null,role,capabilities:{...common,dashboard:grant(),family_workspace:grant(),discover:grant(),coaches:grant(),notes:grant(true,true),marketplace:grant(true,false,true,false,true),programs:grant(true,false,true),memberships:grant(true,false,true),payments:grant(true,false,true,false,true),dues:grant(true,false,true),events:grant(true,false,true),registrations:grant(true,false,true),facilities:grant(true,false,true,false,true),fundraising:grant(true,false,true),organizations_teams:grant(),waivers:grant(true,true)}})
