import {NextResponse} from 'next/server'
import {createRouteHandlerClientCompat} from '@/lib/routeHandlerSupabase'
import {supabaseAdmin} from '@/lib/supabaseAdmin'
export const dynamic='force-dynamic'
const fail=(message:string,status=400)=>NextResponse.json({error:message},{status})
const normalize=(value:unknown):Record<string,boolean>=>Array.isArray(value)?Object.fromEntries(value.filter(x=>typeof x==='string').map(x=>[x,true])):value&&typeof value==='object'?Object.fromEntries(Object.entries(value).filter(([,v])=>typeof v==='boolean')):{}
async function access(orgId:string){const supabase=await createRouteHandlerClientCompat(),{data:{session}}=await supabase.auth.getSession();if(!session)return{response:fail('Unauthorized',401),supabase};const{data}=await supabase.rpc('can_manage_org_staff',{p_org_id:orgId,p_user_id:session.user.id});return{response:data===true?null:fail('Organization staff management permission is required.',403),supabase}}
export async function GET(request:Request){const orgId=new URL(request.url).searchParams.get('org_id')||'';if(!orgId)return fail('org_id is required');const a=await access(orgId);if(a.response)return a.response;const[{data:roles,error},{data:assignments}]=await Promise.all([supabaseAdmin.from('organization_role_definitions').select('id,role_key,display_name,description,permissions,is_active,updated_at').eq('org_id',orgId).eq('is_active',true).order('display_name'),supabaseAdmin.from('organization_role_assignments').select('id,role_definition_id,user_id,scope_type,scope_id').eq('org_id',orgId)]);if(error)return fail('Unable to load custom roles.',500);return NextResponse.json({roles:(roles||[]).map(role=>({...role,permissions:normalize(role.permissions)})),assignments:assignments||[]})}
export async function POST(request:Request){const body=await request.json().catch(()=>({})),orgId=String(body.org_id||''),roleKey=String(body.role_key||'').trim(),displayName=String(body.display_name||'').trim();if(!orgId||!roleKey||!displayName)return fail('Organization, role key, and display name are required.');const a=await access(orgId);if(a.response)return a.response;const{data,error}=await a.supabase.rpc('upsert_organization_role',{p_org_id:orgId,p_role_key:roleKey,p_display_name:displayName,p_description:body.description||null,p_permissions:normalize(body.permissions)});if(error)return fail(error.message,400);return NextResponse.json({role_definition_id:data})}
export async function PATCH(request:Request){const body=await request.json().catch(()=>({})),orgId=String(body.org_id||''),roleId=String(body.role_definition_id||''),userId=String(body.user_id||'');if(!orgId||!roleId||!userId)return fail('Organization, role, and staff member are required.');const a=await access(orgId);if(a.response)return a.response;const{data,error}=await a.supabase.rpc('assign_organization_role',{p_org_id:orgId,p_role_definition_id:roleId,p_user_id:userId,p_scope_type:'organization',p_scope_id:null});if(error)return fail(error.message,400);return NextResponse.json({assignment_id:data})}
