'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'

type League = { id:string; name:string; sport?:string|null; general_location?:string|null; description?:string|null; contact_email?:string|null; contact_phone?:string|null; profile_image_url?:string|null; website_url?:string|null; accepting_join_requests:boolean; organization_count:number; team_count:number; division_count:number }
type Option = { id?:string; org_id?:string; full_name?:string; organizations?:{name?:string}|Array<{name?:string}> }

export default function LeaguePublicProfileClient({ leagueId }: { leagueId: string }) {
  const [league,setLeague]=useState<League|null>(null), [loading,setLoading]=useState(true), [error,setError]=useState('')
  const [joinOpen,setJoinOpen]=useState(false), [joinError,setJoinError]=useState(''), [notice,setNotice]=useState('')
  const [type,setType]=useState('organization'), [message,setMessage]=useState(''), [orgId,setOrgId]=useState(''), [athleteId,setAthleteId]=useState('')
  const [organizations,setOrganizations]=useState<Option[]>([]), [athletes,setAthletes]=useState<Option[]>([]), [signedIn,setSignedIn]=useState<boolean|null>(null)
  useEffect(()=>{ fetch(`/api/public/leagues/${leagueId}`).then(async r=>({ok:r.ok,data:await r.json()})).then(({ok,data})=>{if(!ok)throw new Error(data.error||'League unavailable');setLeague(data.league)}).catch(e=>setError(e.message)).finally(()=>setLoading(false)) },[leagueId])
  const openJoin=async()=>{setJoinError('');const r=await fetch(`/api/leagues/${leagueId}/join`);if(r.status===401){setSignedIn(false);setJoinOpen(true);return}const data=await r.json();if(!r.ok){setJoinError(data.error||'Unable to load your profiles.');setJoinOpen(true);return}setSignedIn(true);setOrganizations(data.organizations||[]);setAthletes(data.athletes||[]);setOrgId(data.organizations?.[0]?.org_id||'');setAthleteId(data.athletes?.[0]?.id||'');setJoinOpen(true)}
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setJoinError('');const r=await fetch(`/api/leagues/${leagueId}/join`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({requester_type:type,org_id:orgId||null,athlete_id:athleteId||null,message})});const data=await r.json();if(!r.ok){setJoinError(data.error||'Unable to submit request.');return}setNotice('Your request was sent to the league.');setJoinOpen(false)}
  if(loading)return <main className="min-h-[70vh] px-5 py-14"><p className="mx-auto max-w-5xl">Loading league…</p></main>
  if(error||!league)return <main className="min-h-[70vh] px-5 py-14"><p className="mx-auto max-w-3xl rounded-2xl bg-red-50 p-5 text-red-800">{error||'League unavailable'}</p></main>
  const optionName=(item:Option)=>Array.isArray(item.organizations)?item.organizations[0]?.name:item.organizations?.name
  return <main className="min-h-[75vh] bg-[#f9f9f9] px-5 py-12"><div className="mx-auto max-w-5xl">
    <section className="rounded-[2rem] border border-[#dcdcdc] bg-white p-7 shadow-sm sm:p-10"><div className="flex flex-wrap items-start justify-between gap-6"><div className="flex items-center gap-5">{league.profile_image_url?<img src={league.profile_image_url} alt="" className="h-20 w-20 rounded-2xl border object-cover"/>:<div className="flex h-20 w-20 items-center justify-center rounded-2xl bg-[#191919] text-3xl font-bold text-white">{league.name.slice(0,1)}</div>}<div><p className="text-xs font-bold uppercase tracking-[.25em] text-[#b80f0a]">Public league</p><h1 className="mt-2 text-4xl font-semibold">{league.name}</h1><p className="mt-2 text-[#4a4a4a]">{[league.sport,league.general_location].filter(Boolean).join(' · ')||'League details'}</p></div></div>{league.accepting_join_requests?<button onClick={openJoin} className="rounded-full bg-[#b80f0a] px-5 py-3 text-sm font-semibold text-white">Request to join</button>:<span className="rounded-full bg-[#f1f1f1] px-4 py-2 text-sm">Join requests closed</span>}</div>{league.description?<p className="mt-7 max-w-3xl leading-7 text-[#4a4a4a]">{league.description}</p>:null}</section>
    <section className="mt-6 grid gap-4 sm:grid-cols-3">{[['Organizations',league.organization_count],['Teams',league.team_count],['Divisions',league.division_count]].map(([label,value])=><div key={String(label)} className="rounded-3xl border bg-white p-6"><p className="text-3xl font-semibold">{value}</p><p className="mt-1 text-sm text-[#6b6b6b]">{label}</p></div>)}</section>
    {(league.contact_email||league.contact_phone||league.website_url)?<section className="mt-6 rounded-3xl border bg-white p-6"><h2 className="text-lg font-semibold">Public contact</h2><div className="mt-3 flex flex-wrap gap-4 text-sm">{league.contact_email?<a className="text-[#b80f0a] underline" href={`mailto:${league.contact_email}`}>{league.contact_email}</a>:null}{league.contact_phone?<a className="text-[#b80f0a] underline" href={`tel:${league.contact_phone}`}>{league.contact_phone}</a>:null}{league.website_url?<a className="text-[#b80f0a] underline" href={league.website_url} rel="noreferrer" target="_blank">League website</a>:null}</div></section>:null}
    {notice?<p className="mt-6 rounded-2xl bg-emerald-50 p-4 text-emerald-800">{notice}</p>:null}
    {joinOpen?<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><section className="w-full max-w-lg rounded-3xl bg-white p-7"><div className="flex justify-between"><h2 className="text-2xl font-semibold">Request participation</h2><button onClick={()=>setJoinOpen(false)} aria-label="Close">✕</button></div>{signedIn===false?<div className="mt-5"><p className="text-sm text-[#4a4a4a]">Sign in first so the league can verify who is requesting access.</p><Link href={`/login?next=${encodeURIComponent(`/leagues/${leagueId}`)}`} className="mt-4 inline-flex rounded-full bg-[#191919] px-5 py-3 text-sm font-semibold text-white">Sign in</Link></div>:<form onSubmit={submit} className="mt-5 space-y-4"><label className="block text-sm font-semibold">I am requesting as<select value={type} onChange={e=>setType(e.target.value)} className="mt-1 w-full rounded-xl border p-3"><option value="organization">Organization</option><option value="coach">Coach</option><option value="athlete">Athlete or parent</option><option value="other">Other</option></select></label>{type==='organization'?<select required value={orgId} onChange={e=>setOrgId(e.target.value)} className="w-full rounded-xl border p-3"><option value="">Choose an organization</option>{organizations.map(o=><option key={o.org_id} value={o.org_id}>{optionName(o)||'Organization'}</option>)}</select>:null}{type==='athlete'?<select required value={athleteId} onChange={e=>setAthleteId(e.target.value)} className="w-full rounded-xl border p-3"><option value="">Choose an athlete</option>{athletes.map(a=><option key={a.id} value={a.id}>{a.full_name||'Athlete'}</option>)}</select>:null}<textarea value={message} onChange={e=>setMessage(e.target.value)} maxLength={2000} placeholder="Message to the league (optional)" className="min-h-28 w-full rounded-xl border p-3"/>{joinError?<p className="text-sm text-red-700">{joinError}</p>:null}<button className="w-full rounded-full bg-[#b80f0a] px-5 py-3 font-semibold text-white">Send request</button></form>}</section></div>:null}
  </div></main>
}
