'use client'

import { useCallback, useEffect, useState } from 'react'
import AdminSidebar from '@/components/AdminSidebar'

const Section = ({ title, items, busy, update }: { title: string; items: any[]; busy: string; update: (item:any,status:'open'|'checked'|'resolved')=>void }) => <section className="rounded-3xl border bg-white p-5">
  <h2 className="text-xl font-bold">{title} <span className="text-sm font-normal text-neutral-500">({items.length})</span></h2>
  <div className="mt-4 space-y-3">{items.length === 0 ? <p className="text-sm text-neutral-500">No issues in this section.</p> : items.map(item => <article className="rounded-2xl border p-4" key={item.event_id}>
    <div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><p className="text-xs font-bold uppercase text-[#b80f0a]">{item.source} · {item.severity}</p><h3 className="font-bold">{item.event_type}</h3><p className="text-sm text-neutral-600">{item.error_detail || 'No detail supplied.'}</p><p className="mt-2 text-xs text-neutral-500">{item.workspace?.display_name || item.workspace_id || 'No workspace'} · {item.occurred_at ? new Date(item.occurred_at).toLocaleString() : '—'}</p>{item.review_note ? <div className="mt-3 rounded-xl bg-neutral-100 p-3 text-sm"><p>{item.review_note}</p><p className="mt-1 text-xs text-neutral-500">{item.reviewer_name || 'Reviewer unavailable'} · {item.reviewed_at ? new Date(item.reviewed_at).toLocaleString() : '—'}</p></div> : null}</div>
    <div className="flex flex-wrap gap-2">{item.review_status === 'open' ? <><button disabled={busy===item.event_id} onClick={()=>update(item,'checked')} className="rounded-full border px-3 py-2 text-sm font-semibold">Mark Checked</button><button disabled={busy===item.event_id} onClick={()=>update(item,'resolved')} className="rounded-full bg-[#191919] px-3 py-2 text-sm font-semibold text-white">Mark Resolved</button></> : <button disabled={busy===item.event_id} onClick={()=>update(item,'open')} className="rounded-full bg-[#b80f0a] px-3 py-2 text-sm font-semibold text-white">Reopen</button>}</div></div>
  </article>)}</div>
</section>

export default function StripeReconciliationPage() {
  const [data,setData]=useState<any>({sections:{open:[],checked:[],resolved:[]},summary:{}}),[busy,setBusy]=useState(''),[notice,setNotice]=useState(''),[showTestData,setShowTestData]=useState(false)
  const load=useCallback(async()=>{const response=await fetch(`/api/admin/stripe-reconciliation${showTestData?'?show_test_data=true':''}`,{cache:'no-store'});const payload=await response.json().catch(()=>({}));setData(response.ok?payload:{sections:{open:[],checked:[],resolved:[]},summary:{}});setNotice(response.ok?'':payload.error||'Unable to load Stripe reconciliation.')},[showTestData])
  useEffect(()=>{void load()},[load])
  const update=async(item:any,status:'open'|'checked'|'resolved')=>{const note=window.prompt(status==='checked'?'What did you review?':status==='resolved'?'How was the underlying issue confirmed fixed?':'Why does this issue require attention again?')?.trim();if(!note)return;setBusy(item.event_id);const response=await fetch('/api/admin/stripe-reconciliation',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({issue_key:item.event_id,title:item.event_type||item.source,detail:item.error_detail,status,note})});const payload=await response.json().catch(()=>({}));setNotice(response.ok?'Operational review status updated. No financial state was changed.':payload.error||'Unable to update issue.');if(response.ok)await load();setBusy('')}
  return <main className="page-shell"><div className="relative z-10 px-6 py-10"><div className="grid items-start gap-6 lg:grid-cols-[200px_minmax(0,1fr)]"><AdminSidebar/><div className="min-w-0 space-y-6"><header><p className="text-xs font-bold uppercase tracking-[.24em] text-[#b80f0a]">Payments</p><h1 className="text-3xl font-bold">Stripe Reconciliation</h1><p className="text-sm text-neutral-600">Review tracking only. Stripe and backend webhooks remain authoritative for every payment, subscription, booking, refund, and Connect account.</p><label className="mt-3 flex items-center gap-2 text-sm font-semibold"><input type="checkbox" checked={showTestData} onChange={event=>setShowTestData(event.target.checked)}/>Show test data</label></header>{notice?<p className="rounded-2xl border bg-white p-3 text-sm">{notice}</p>:null}<div className="grid gap-3 sm:grid-cols-3"><div className="rounded-3xl border bg-white p-5">Open<strong className="block text-3xl">{data.summary?.open||0}</strong></div><div className="rounded-3xl border bg-white p-5">Critical<strong className="block text-3xl">{data.summary?.critical||0}</strong></div><div className="rounded-3xl border bg-white p-5">Warnings<strong className="block text-3xl">{data.summary?.warning||0}</strong></div></div><Section title="Open" items={data.sections?.open||[]} busy={busy} update={update}/><Section title="Checked History" items={data.sections?.checked||[]} busy={busy} update={update}/><Section title="Resolved History" items={data.sections?.resolved||[]} busy={busy} update={update}/></div></div></div></main>
}
