import { NextResponse } from 'next/server'
import { getSessionRole, jsonError } from '@/lib/apiAuth'
import { supabaseAdmin } from '@/lib/supabaseAdmin'
const ROLES = ['org_admin','club_admin','travel_admin','school_admin','athletic_director','program_director','team_manager','admin']
async function orgFor(id: string) { const { data } = await supabaseAdmin.from('organization_memberships').select('org_id').eq('user_id', id).maybeSingle(); return data?.org_id || null }
export async function GET() { const { session, error } = await getSessionRole(ROLES); if (error || !session) return error; const orgId = await orgFor(session.user.id); if (!orgId) return jsonError('Organization not found', 404); const { data, error: q } = await supabaseAdmin.from('org_compliance_items').select('*').eq('org_id', orgId).order('due_date'); if (q) return jsonError(q.message, 500); return NextResponse.json({ items: data || [] }) }
export async function POST(request: Request) { const { session, error } = await getSessionRole(ROLES); if (error || !session) return error; const orgId = await orgFor(session.user.id); if (!orgId) return jsonError('Organization not found', 404); const body = await request.json().catch(() => ({})); const title = String(body.title || '').trim(); if (!title) return jsonError('title is required'); const { data, error: q } = await supabaseAdmin.from('org_compliance_items').insert({ org_id: orgId, title, description: body.description || null, due_date: body.due_date || null }).select('*').single(); if (q) return jsonError(q.message, 500); return NextResponse.json({ item: data }, { status: 201 }) }
export async function PATCH(request: Request) { const { session, error } = await getSessionRole(ROLES); if (error || !session) return error; const orgId = await orgFor(session.user.id); if (!orgId) return jsonError('Organization not found', 404); const body = await request.json().catch(() => ({})); if (!body.id || !['pending','complete','overdue','waived'].includes(body.status)) return jsonError('id and valid status are required'); const { error: q } = await supabaseAdmin.from('org_compliance_items').update({ status: body.status, updated_at: new Date().toISOString() }).eq('id', body.id).eq('org_id', orgId); if (q) return jsonError(q.message, 500); return NextResponse.json({ ok: true }) }
export async function DELETE(request: Request) { const { session, error } = await getSessionRole(ROLES); if (error || !session) return error; const orgId = await orgFor(session.user.id); if (!orgId) return jsonError('Organization not found', 404); const id = new URL(request.url).searchParams.get('id'); if (!id) return jsonError('id is required'); const { error: q } = await supabaseAdmin.from('org_compliance_items').delete().eq('id', id).eq('org_id', orgId); if (q) return jsonError(q.message, 500); return NextResponse.json({ ok: true }) }
