import {NextResponse} from 'next/server'
import {createClient} from '@supabase/supabase-js'
import {createRouteHandlerClientCompat} from '@/lib/routeHandlerSupabase'
import {supabaseAdmin} from '@/lib/supabaseAdmin'
export const dynamic='force-dynamic'
const STAFF_ROLES=['owner','org_admin','admin','program_director','team_manager','coach','assistant_coach']
const fail=(message:string,status=400)=>NextResponse.json({error:message},{status})
async function actorClient(request:Request){const cookieClient=await createRouteHandlerClientCompat(),{data:{session}}=await cookieClient.auth.getSession();if(session?.user)return{user:session.user,supabase:cookieClient};const token=request.headers.get('authorization')?.match(/^Bearer\s+(.+)$/i)?.[1]?.trim();if(!token)return null;const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,{global:{headers:{Authorization:`Bearer ${token}`}},auth:{persistSession:false,autoRefreshToken:false}}),{data:{user},error}=await supabase.auth.getUser(token);return error||!user?null:{user,supabase}}
async function authorized(request:Request,orgId:string){const actor=await actorClient(request);if(!actor)return{response:fail('Unauthorized',401)};const{data,error}=await actor.supabase.rpc('can_manage_org_staff',{p_org_id:orgId,p_user_id:actor.user.id});if(error||data!==true)return{response:fail('Organization staff management permission is required.',403)};return{...actor,response:null}}
export async function GET(request:Request){const orgId=new URL(request.url).searchParams.get('org_id')?.trim()||'';if(!orgId)return fail('org_id is required');const access=await authorized(request,orgId);if(access.response)return access.response;const{data:memberships,error}=await supabaseAdmin.from('organization_memberships').select('id,user_id,role,status,created_at').eq('org_id',orgId).in('role',STAFF_ROLES).order('created_at');if(error)return fail('Unable to load organization staff.',500);const userIds=Array.from(new Set((memberships||[]).map(row=>row.user_id))),{data:profiles}=userIds.length?await supabaseAdmin.from('profiles').select('id,full_name,email').in('id',userIds):{data:[]};const byId=new Map((profiles||[]).map(row=>[row.id,row]));return NextResponse.json({members:(memberships||[]).map(row=>({...row,full_name:byId.get(row.user_id)?.full_name||null,email:byId.get(row.user_id)?.email||null}))})}
export async function PATCH(request:Request){const body=await request.json().catch(()=>({})),orgId=String(body.org_id||''),membershipId=String(body.membership_id||''),role=String(body.role||'');if(!orgId||!membershipId||!role)return fail('org_id, membership_id, and role are required');const access=await authorized(request,orgId);if(access.response)return access.response;const{data,error}=await access.supabase.rpc('update_my_org_member_access',{p_org_id:orgId,p_membership_id:membershipId,p_role:role,p_remove:false});if(error)return fail(error.message.includes('unsupported_organization_role')?'That staff role is not supported.':error.message.includes('management_required')?'Organization staff management permission is required.':'Unable to update staff access.',error.code==='42501'?403:400);return NextResponse.json(data||{ok:true})}
export async function DELETE(request:Request){const body=await request.json().catch(()=>({})),orgId=String(body.org_id||''),membershipId=String(body.membership_id||'');if(!orgId||!membershipId)return fail('org_id and membership_id are required');const access=await authorized(request,orgId);if(access.response)return access.response;const{data,error}=await access.supabase.rpc('update_my_org_member_access',{p_org_id:orgId,p_membership_id:membershipId,p_role:null,p_remove:true});if(error)return fail(error.message.includes('cannot_remove_yourself')?'You cannot remove your own administrator access.':error.message.includes('management_required')?'Organization staff management permission is required.':'Unable to remove staff access.',error.code==='42501'?403:400);const{error:cleanupError}=await supabaseAdmin.from('organization_memberships').delete().eq('id',membershipId).eq('org_id',orgId).eq('status','suspended');if(cleanupError)return fail('Staff access was removed, but the legacy membership could not be finalized.',500);return NextResponse.json(data||{ok:true})}
export async function POST(request:Request){const body=await request.json().catch(()=>({})),orgId=String(body.org_id||''),userId=String(body.user_id||'');if(body.action!=='remove_coach'||!orgId||!userId)return fail('org_id, user_id, and action are required');const access=await authorized(request,orgId);if(access.response)return access.response;const{data,error}=await access.supabase.rpc('remove_my_org_coach',{p_org_id:orgId,p_user_id:userId});if(error)return fail(error.message.includes('management_required')?'Organization staff management permission is required.':'Unable to remove coach access.',error.code==='42501'?403:400);return NextResponse.json(data||{ok:true})}
