import{test,expect}from'@playwright/test'
import{readFileSync}from'node:fs'
const read=(path:string)=>readFileSync(path,'utf8')

test('calendar events use authoritative multi-coach assignments and scoped rosters',()=>{const sql=read('supabase/migrations/20261010120000_calendar_event_coach_assignments.sql');expect(sql).toContain('org_calendar_event_coaches');expect(sql).toContain('set_org_calendar_event_coaches');expect(sql).toContain('my_org_calendar_event_roster');expect(sql).toContain('a.coach_id=auth.uid()');expect(sql).toContain('coach_not_active_in_organization')})
test('free events stay outside payment and registration tables',()=>{const calendar=read('src/app/org/calendar/page.tsx');expect(calendar).toContain("from('practice_plans').insert");expect(calendar).toContain("rpc('set_org_calendar_event_coaches'");expect(calendar).not.toContain("from('org_training_sessions').insert");expect(calendar).not.toContain('drop_in_price_cents')})
test('paid training uses session records, pricing, recurrence, and per-occurrence assignments',()=>{const page=read('src/app/org/training-sessions/page.tsx');expect(page).toContain("from('org_training_sessions').insert");expect(page).toContain('drop_in_price_cents');expect(page).toContain("form.recurrence==='weekly'");expect(page).toContain("rpc('set_org_training_session_coaches'");expect(page).not.toContain("from('practice_plans').insert")})
test('coach workspace includes assigned calendar events and their roster RPC',()=>{const page=read('src/app/coach/organization-assignments/page.tsx');expect(page).toContain('org_calendar_event_coaches');expect(page).toContain('my_org_calendar_event_roster');expect(page).toContain("kind:'calendar_event'")})
test('organization managers can create edit and roster free practices and games',()=>{const page=read('src/app/org/calendar-events/page.tsx');expect(page).toContain("from('practice_plans').insert");expect(page).toContain("from('practice_plans').update");expect(page).toContain("rpc('set_org_calendar_event_coaches'");expect(page).toContain("rpc('my_org_calendar_event_roster'");expect(page).toContain('Assigned coaches')})
