import{test,expect}from'@playwright/test'
import{readFileSync}from'node:fs'
const read=(path:string)=>readFileSync(path,'utf8')

test('owner and org admin resolve complete organization capabilities',()=>{const lib=read('src/lib/portalCapabilities.ts');expect(lib).toContain("new Set(['owner','org_admin'");expect(lib).toContain("messages:grant(true,permission('send_messages'))");expect(lib).toContain("coaches:grant(true,permission('manage_coaches'))");expect(lib).toContain("permissions:grant(permission('manage_permissions'),permission('manage_permissions'))")})
test('program director receives operational defaults without implicit billing or permission administration',()=>{const lib=read('src/lib/portalCapabilities.ts');expect(lib).toContain("role==='program_director'");expect(lib).toContain('PROGRAM_DIRECTOR_DEFAULTS');expect(lib).not.toContain("'manage_billing','manage_permissions'");expect(lib).toContain("billing:grant(permission('manage_billing')||payments")})
test('ordinary organization coaches receive the scoped coach document',()=>{const lib=read('src/lib/portalCapabilities.ts');expect(lib).toContain("['coach','assistant_coach'].includes(activeRole)");expect(lib).toContain('organizationCoachDocument(workspace,activeRole)');expect(lib).toContain("payments:grant(permission('view_org_finance'))")})
test('mobile endpoint distinguishes workspace denial from capability resolution failure',()=>{const route=read('src/app/api/mobile/capabilities/route.ts');expect(route).toContain("'workspace_forbidden'");expect(route).toContain("'invalid_acting_role'");expect(route).toContain("'capability_resolution_failed'");expect(route).toContain('503,true');expect(route).not.toContain('No portal capabilities are available')})
test('mobile endpoint canonicalizes workspace organization and acting role',()=>{const route=read('src/app/api/mobile/capabilities/route.ts');expect(route).toContain("searchParams.get('organization_id')||url.searchParams.get('org_id')");expect(route).toContain("headers.get('x-acting-role')||url.searchParams.get('acting_role')");expect(route).toContain('headerWorkspaceId&&queryWorkspaceId&&headerWorkspaceId!==queryWorkspaceId');expect(route).toContain('resolvePortalCapabilities(auth.user.id,workspaceId,workspace.organizationId,actingRole)')})
test('subscription status preserves scheduled-cancellation and terminal period fields',()=>{const route=read('src/app/api/mobile/subscription/status/route.ts'),lib=read('src/lib/platformSubscription.ts');expect(route).toContain('...snapshot');expect(lib).toContain("if (normalized === 'active') return true");expect(lib).toContain("value === 'canceled'");expect(lib).toContain('current_period_end: stripePeriodEnd');expect(lib).toContain('cancel_at_period_end: stripeSubscription?.cancel_at_period_end');expect(lib).toContain('data.current_period_end || null')})
