import { test, expect } from '@playwright/test'
import fs from 'node:fs'
import path from 'node:path'
import { normalizeUuid } from '../src/lib/uuid'

const source = (file: string) => fs.readFileSync(path.join(process.cwd(), file), 'utf8')

test('UUID comparison treats mixed-case request values as the same workspace', () => {
  const lowercase = 'd5605c4e-e99c-490d-bd91-83cd717f7061'
  const uppercase = 'D5605C4E-E99C-490D-BD91-83CD717F7061'
  expect(normalizeUuid(lowercase)).toBe(normalizeUuid(uppercase))
})

test('signup preserves organization and league administrator identities', () => {
  const route = source('src/app/api/auth/signup/route.ts')
  expect(route).toContain("'league_admin'")
  expect(route).toContain("roles: ['owner', 'org_admin']")
  expect(route).not.toContain("roles: ['owner', 'org_admin', 'coach']")
  expect(route).toContain("workspace_type: 'league'")
  expect(route).toContain("roles: ['owner', 'league_admin']")
  expect(route).toContain('plan_key: selectedTier')
  expect(route).toContain('request_id: requestId')
})

test('mobile subscription checkout is workspace-bound and returns specific consent errors', () => {
  const route = source('src/app/api/mobile/subscription/start/route.ts')
  expect(route).toContain('authorizeWorkspaceRequest')
  expect(route).toContain('normalizeUuid(rawBodyWorkspaceId)')
  expect(route).toContain('logWorkspaceAuthority')
  expect(route).toContain('normalizeUuid(prior.workspace_id) !== workspaceId')
  expect(route).toContain("'The selected workspace could not be authorized.'")
  expect(route).toContain('body.organization_consent')
  expect(route).toContain('body.authority_accepted === true')
  expect(route).toContain('body.recurring_billing_accepted === true')
  expect(route).toContain('body.minor_data_accepted === true')
  expect(route).toContain("code: 'organization_consent_required'")
  for (const field of ['authority_accepted', 'recurring_billing_accepted', 'minor_data_accepted']) expect(route).toContain(`'${field}'`)
  expect(route).toContain("code: 'agreement_version_mismatch'")
  expect(route).toContain('const MOBILE_AGREEMENT_VERSION = ORGANIZATION_AGREEMENT_VERSION')
  expect(route).toContain('expected_agreement_version: MOBILE_AGREEMENT_VERSION')
  expect(route).toContain("'X-Idempotent-Replay': 'true'")
  expect(route).toContain("mode: 'subscription'")
  expect(route).toContain("stripe.prices.retrieve(priceId)")
  expect(route).toContain("select('email,full_name,stripe_customer_id')")
  expect(route).toContain('prior?.stripe_customer_id || profile?.stripe_customer_id')
  expect(route).toContain('stripe.customers.retrieve(customerId)')
  expect(route).toContain('subscription-customer:v2:')
  expect(route).toContain("configuredPrice.type !== 'recurring'")
  expect(route).toContain("configuredPrice.recurring?.interval !== billingInterval")
  expect(route).toContain("configuredPrice.livemode !== keyIsLive")
  expect(route).toContain("checkoutStage = 'persist_organization_legal_acceptance'")
  expect(route).toContain("from('workspace_subscription_consents').upsert")
  expect(route).toContain("status: 'incomplete'")
  expect(route).toContain('request_id: requestId')
})

test('league enterprise is explicit contact-required until self service is enabled', () => {
  const pricing = source('src/lib/allAccessPricing.ts')
  const route = source('src/app/api/mobile/subscription/start/route.ts')
  expect(pricing).toContain("league_enterprise: { key: 'league_enterprise'")
  expect(pricing).toContain('selfService: false')
  expect(route).toContain("'contact_required'")
})

test('billing portal derives the Stripe customer from the selected owner subscription', () => {
  const route = source('src/app/api/mobile/billing-portal/route.ts')
  expect(route).toContain('resolveMobileSubscriptionOwner')
  expect(route).toContain('authorizeWorkspaceRequest')
  expect(route).toContain('logWorkspaceAuthority')
  expect(route).toContain('normalizeUuid(subscription.workspace_id) !== workspaceId')
  expect(route).toContain("'The selected workspace could not be authorized.'")
  expect(route).toContain("from('platform_subscriptions')")
  expect(route).toContain("'subscription_workspace_mismatch'")
  expect(route).toContain("'apple_managed_subscription'")
  expect(route).toContain("'stripe_customer_deleted'")
  expect(route).toContain('STRIPE_ORGANIZATION_SUBSCRIPTION_PORTAL_CONFIGURATION_ID')
  expect(route).not.toContain('STRIPE_RECURRING_FEES_PORTAL_CONFIGURATION_ID')
  expect(route).toContain("'billing_portal_unavailable'")
  expect(route).toContain("'Unable to open subscription management.'")
  expect(route).toContain("https://app.coacheshive.com/open-app?from=%2Fbilling-updated")
  expect(route).toContain('expires_at:')
  expect(route).toContain('request_id: requestId')
})

test('Stripe webhook persists league subscription and cancellation state', () => {
  const webhook = source('src/app/api/stripe/webhook/route.ts')
  expect(webhook).toContain("metadata.owner_type === 'league'")
  expect(webhook).toContain("event.type === 'customer.subscription.deleted' ? 'canceled'")
  expect(webhook).toContain("owner_type: 'league'")
  expect(webhook).toContain("from('workspace_subscription_consents').update")
  expect(webhook).toContain('workspaceId: metadata.workspace_id || null')
  expect(webhook).toContain('planKey: metadata.plan_key || null')
})

test('Stripe webhook treats both successful invoice event variants as paid', () => {
  const webhook = source('src/app/api/stripe/webhook/route.ts')
  expect(webhook).toContain("event.type === 'invoice.payment_succeeded' || event.type === 'invoice.paid'")
  expect(webhook).toContain('subscriptionStatus: paymentSucceeded')
  expect(webhook).toContain('subscription_status: paymentSucceeded')
  expect(webhook).toContain("'[stripe/webhook] rejected invalid signature'")
})

test('Single Team athlete invitations are workspace-bound, tokenized, and delivery-confirmed', () => {
  const invite = source('src/app/api/invites/athlete/route.ts')
  const accept = source('src/app/api/invitations/accept/route.ts')
  expect(invite).toContain('authorizeWorkspaceRequest')
  expect(invite).toContain('logWorkspaceAuthority')
  expect(invite).toContain("workspace.type === 'independent_coach'")
  expect(invite).toContain("workspaceCan(workspace, 'manage_members')")
  expect(invite).toContain('hashInviteToken(token)')
  expect(invite).toContain("invitationResult.error?.code === '23505'")
  expect(invite).toContain("delivery.status !== 'sent'")
  expect(invite).toContain("reject('invitation_delivery_failed'")
  expect(invite).toContain("code: 'athlete_invitation_failed'")
  expect(invite).toContain("message: 'We couldn’t send the invitation. Please try again.'")
  expect(invite).toContain("success: true, invitation_id: invitationId, status: 'pending'")
  expect(accept).toContain("from('coach_athlete_invitations')")
  expect(accept).toContain("workspace.workspace_type === 'organization'")
  expect(accept).toContain("workspace.workspace_type !== 'league'")
  expect(accept).toContain("from('coach_athlete_links').upsert")
  expect(accept).toContain("from('athlete_organization_memberships').upsert")
  expect(accept).toContain("from('workspace_memberships').upsert")
})
