import { test, expect } from '@playwright/test'
import fs from 'node:fs';import path from 'node:path'
const root=process.cwd(),read=(p:string)=>fs.readFileSync(path.join(root,p),'utf8')
const routes=[
 'src/app/api/mobile/registrations/route.ts','src/app/api/mobile/registrations/[id]/route.ts','src/app/api/mobile/registrations/[id]/submit/route.ts','src/app/api/mobile/registrations/[id]/intent/route.ts',
 'src/app/api/mobile/org/dues/route.ts','src/app/api/mobile/dues/[installmentId]/intent/route.ts','src/app/api/mobile/dues/[installmentId]/autopay/route.ts','src/app/api/mobile/dues/[installmentId]/waive/route.ts','src/app/api/mobile/dues/[installmentId]/mark-off-platform/route.ts',
 'src/app/api/mobile/org/payment-events/route.ts','src/app/api/mobile/events/[obligationId]/intent/route.ts','src/app/api/mobile/facilities/route.ts','src/app/api/mobile/facilities/[spaceId]/intent/route.ts','src/app/api/mobile/facility-bookings/[bookingId]/cancel/route.ts','src/app/api/mobile/org/fundraising/route.ts','src/app/api/mobile/fundraising/[campaignId]/intent/route.ts','src/app/api/mobile/payments/dashboard/route.ts']
test('all required mobile payment routes exist and use shared bearer auth',()=>{for(const route of routes){expect(fs.existsSync(path.join(root,route)),route).toBeTruthy();expect(read(route)).toMatch(/requireMobile(User|OrgAuthority)/)}})
test('canonical intent requires idempotency and creates pending integer-cent ledger record',()=>{const code=read('src/lib/canonicalPaymentIntent.ts');expect(code).toContain('stripeIdempotencyKey');expect(code).toContain("status: 'pending'");for(const field of ['amount_cents','platform_fee_cents','stripe_processing_fee_cents','net_cents'])expect(code).toContain(field);expect(code).toContain("processingFeeRate.toFixed(2)")})
test('clients cannot supply authoritative fee or destination values',()=>{for(const route of routes.filter(x=>x.includes('/intent/'))){const code=read(route);expect(code).not.toMatch(/body\.(processing_fee_rate|application_fee_amount|platform_fee_cents|net_cents|connected_account_id)/)}})
test('webhook remains authoritative for success failure refunds invoices and Connect',()=>{const code=read('src/app/api/stripe/webhook/route.ts');for(const event of ['payment_intent.succeeded','payment_intent.payment_failed','charge.refunded','invoice.payment_succeeded','invoice.payment_failed','account.updated'])expect(code).toContain(event)})
test('responsive web surfaces cover every launched collection category',()=>{for(const page of ['src/app/org/collections/page.tsx','src/app/pay/[slug]/page.tsx','src/app/facilities/page.tsx','src/app/coach/payments/page.tsx','src/app/athlete/payments/page.tsx'])expect(fs.existsSync(path.join(root,page))).toBeTruthy();expect(read('src/app/org/collections/page.tsx')).toContain('Future payment categories')})
