import { expect, test } from '@playwright/test'
import fs from 'node:fs'
import path from 'node:path'

const root = process.cwd()
const read = (file: string) => fs.readFileSync(path.join(root, file), 'utf8')

test('training package purchase RPC is tenant-safe and reloads PostgREST', () => {
  const sql = read('supabase/migrations/20261001050000_restore_training_package_purchase_request.sql')
  expect(sql).toContain('request_org_training_package_purchase')
  expect(sql).toContain('my_accessible_athlete_profiles()')
  expect(sql).toContain("my_accessible_athlete_profiles()")
  expect(sql).toContain("v_package.billing_type='recurring'")
  expect(sql).toContain("status in ('pending','active','past_due')")
  expect(sql).toContain("notify pgrst, 'reload schema'")
})

test('family storefront exposes canonical training-package checkout identifiers', () => {
  const route = read('src/app/api/mobile/family/storefront/route.ts')
  expect(route).toContain("from('org_training_packages')")
  expect(route).toContain("from('org_training_package_purchases')")
  expect(route).toContain("checkout_type:'training_package'")
  expect(route).toContain('checkout_record_id:existing?.id||null')
  expect(route).toContain("trainingPackage.offering_type==='drop_in'")
})

test('payment ledger supports PostgREST idempotent upserts by PaymentIntent', () => {
  const sql = read('supabase/migrations/20261001060000_repair_payment_transaction_idempotency.sql')
  expect(sql).toContain('drop index if exists public.payment_transactions_payment_intent_uidx')
  expect(sql).toMatch(/create unique index payment_transactions_payment_intent_uidx\s+on public\.payment_transactions\(stripe_payment_intent_id\)/)
  expect(sql).not.toContain('where stripe_payment_intent_id is not null')
})

test('training package checkout uses authoritative records and webhook activation', () => {
  const route = read('src/app/api/mobile/training-packages/purchase/route.ts')
  const fulfillment = read('src/lib/mobileCheckoutFulfillment.ts')
  const webhook = read('src/app/api/stripe/webhook/route.ts')
  expect(route).toContain("from('org_training_package_purchases')")
  expect(route).toContain("from('org_training_packages')")
  expect(route).not.toContain("from('athlete_organization_memberships')")
  expect(route).toContain("body.athlete_id || body.athlete_profile_id")
  expect(route).toContain("body.package_id || body.offering_id")
  expect(route).toContain("body.package_id || body.offering_id || '').trim().toLowerCase()")
  expect(route).toContain("body.athlete_id || body.athlete_profile_id || '').trim().toLowerCase()")
  expect(route).toContain("purchaser_user_id: user.id")
  expect(route).toContain("status: 'pending'")
  expect(route).toContain(".update({ purchaser_user_id: user.id")
  expect(route).toContain(".is('stripe_checkout_session_id', null)")
  expect(route).toContain(".is('stripe_subscription_id', null)")
  expect(route).toContain("loadStripeConnectAccountStatus('org', purchase.org_id)")
  expect(route).toContain("loadStripeConnectAccountStatus('org', purchase.org_id, { refresh: true })")
  expect(route).toContain("!isStripeConnectEnabled(connect) || Boolean(connect?.livemode) !== live")
  expect(route).toContain("code: 'connect_setup_incomplete'")
  expect(route).toContain(".order('created_at', { ascending: true }).limit(1).maybeSingle()")
  expect(route).toContain("mode: recurring ? 'subscription' : 'payment'")
  expect(route).toContain("checkout_type: 'training_package'")
  expect(route).toContain("currency: 'usd' as const")
  expect(route).toContain('fee_breakdown: payment')
  for (const field of ['base_amount_cents','service_fee_cents','total_cents','policy_version','agreement_version']) {
    expect(read('src/lib/organizationPaymentPolicy.ts')).toContain(field)
  }
  expect(route).toContain('fulfillMobileCheckoutSession(prior)')
  expect(fulfillment).toContain("type === 'training_package'")
  expect(fulfillment).toContain("rpc('activate_org_training_purchase'")
  expect(fulfillment).toContain('p_cycle_key: cycleKey')
  expect(fulfillment).toContain('p_stripe_invoice_id: invoiceId')
  expect(webhook).toContain("metadata.source === 'org_training_package'")
})

test('review confirmation flows through Stripe redirect, webhook activation, and Billing Portal access', () => {
  const purchase = read('src/app/api/mobile/training-packages/purchase/route.ts')
  const webhook = read('src/app/api/stripe/webhook/route.ts')
  const fulfillment = read('src/lib/mobileCheckoutFulfillment.ts')
  const portal = read('src/app/api/mobile/training-packages/billing-portal/route.ts')
  expect(purchase).toContain('body.authorization_accepted !== true')
  expect(purchase).toContain('stripe.checkout.sessions.create')
  expect(purchase).toContain('checkout_url: assertStripeHostedUrl(session.url)')
  expect(purchase).toContain('purchase_id: purchase.id')
  expect(purchase).toContain('expires_at: expiresAt')
  expect(purchase).toContain('fee_breakdown: payment')
  expect(webhook).toContain("event.type === 'checkout.session.completed'")
  expect(fulfillment).toContain("type === 'training_package'")
  expect(fulfillment).toContain("rpc('activate_org_training_purchase'")
  expect(portal).toContain("['active','past_due'].includes(String(purchase.status))")
  expect(portal).toContain('stripe.billingPortal.sessions.create')
  expect(portal).toContain('portal_url: assertStripeHostedUrl(session.url)')
})

test('training activation migration removes the ambiguous legacy overload', () => {
  const sql = read('supabase/migrations/20261001080000_resolve_training_activation_overload.sql')
  expect(sql).toContain('drop function if exists public.activate_org_training_purchase(uuid,uuid,text,timestamptz)')
  expect(sql).toContain('p_cycle_key text default null')
  expect(sql).toContain('p_stripe_invoice_id text default null')
  expect(sql).toContain('on conflict(purchase_id,cycle_key) do nothing')
})
