import{test,expect}from'@playwright/test'
import fs from'node:fs';import path from'node:path'
const root=process.cwd(),read=(p:string)=>fs.readFileSync(path.join(root,p),'utf8')
test('recipient search is portal scoped private and test-data filtered',()=>{const route=read('src/app/api/mobile/messaging/recipients/route.ts'),lib=read('src/lib/mobileMessagingRecipients.ts'),migration=read('supabase/migrations/20261004010000_authoritative_mobile_messaging_recipients.sql');expect(route).toContain("q.length===1");expect(route).toContain("Math.min(20");expect(route).toContain('resolveAuthorizedAthleteContext');expect(route).toContain('authorizeWorkspaceRequest');expect(lib).toContain("eq('is_test',false)");expect(lib).toContain('allowParentToParentMessaging');expect(lib).toContain('allow_organization_messaging');expect(lib).toContain("message_unavailable_reason='blocked'");expect(lib).not.toContain('.select(\'email');expect(migration).toContain('allow_organization_messaging')})
test('conversation opening requires idempotency and resolves organization contacts server side',()=>{const route=read('src/app/api/mobile/messaging/conversations/route.ts'),lib=read('src/lib/mobileMessagingRecipients.ts'),migration=read('supabase/migrations/20261004010000_authoritative_mobile_messaging_recipients.sql');expect(route).toContain("headers.get('idempotency-key')");expect(route).toContain("rpc('open_family_contact_thread'");expect(route).toContain("rpc('open_family_coach_thread'");expect(route).toContain('resolveOrganizationContact');expect(lib).toContain("rpc('open_mobile_recipient_thread'");expect(migration).toContain('pg_advisory_xact_lock');expect(migration).toContain('unique nulls not distinct');expect(migration).toContain('resolved_recipient_user_id')})
test('organization search resolves active parent and athlete accounts through both ownership keys',()=>{const lib=read('src/lib/mobileMessagingRecipients.ts'),route=read('src/app/api/mobile/messaging/recipients/route.ts');expect(route).toContain("portal==='organization'");expect(route).toContain("expectedType:'organization'");expect(lib).toContain("select('id,full_name,owner_user_id,auth_user_id')");expect(lib).toContain("recipient_type:'parent_athlete'");expect(lib).toContain("athleteAccount?'Athlete':'Parent/Guardian'");expect(lib).toContain("message_unavailable_reason:can?null:'direct_messages_disabled'");expect(lib).toContain('familyAccounts.has(profile.id)')})
test('family search discovers opted-in public family accounts without shared membership',()=>{const lib=read('src/lib/mobileMessagingRecipients.ts'),route=read('src/app/api/mobile/messaging/conversations/route.ts'),sql=read('supabase/migrations/20261004050000_public_family_recipient_messaging.sql'),hardening=read('supabase/migrations/20261005000000_harden_public_family_search_and_atomic_message.sql');expect(lib).toContain('publicFamilyCandidates');expect(lib).toContain("rpc('search_public_family_recipients'");expect(lib).toContain("recipient_type:'parent_athlete'");expect(route).toContain("rpc('open_public_family_thread'");expect(sql).toContain("allowParentToParentMessaging");expect(sql).toContain("ap.birthdate<=current_date-interval '18 years'");expect(sql).toContain('user_blocks');expect(sql).toContain('count(distinct tp.user_id)');expect(sql).not.toContain('athlete_organization_memberships');expect(hardening).toContain("jsonb_typeof(p.athlete_privacy_settings)='object'");expect(hardening).toContain('search_public_family_recipients')})
test('messaging discovery and conversation creation are rate limited',()=>{const search=read('src/app/api/mobile/messaging/recipients/route.ts'),open=read('src/app/api/mobile/messaging/conversations/route.ts');expect(search).toContain("p_action:'messaging_recipient_search'");expect(search).toContain("'messaging_rate_limited'");expect(open).toContain("p_action:'messaging_conversation_open'");expect(open).toContain("'messaging_rate_limited'")})
test('conversation creation can atomically and idempotently send the first message',()=>{const route=read('src/app/api/mobile/messaging/conversations/route.ts'),sql=read('supabase/migrations/20261005000000_harden_public_family_search_and_atomic_message.sql');expect(route).toContain('body.initial_message');expect(route).toContain("rpc('open_mobile_conversation_with_message'");expect(route).toContain("message_status:'sent'");expect(sql).toContain('mobile_conversation_initial_messages');expect(sql).toContain('unique(sender_user_id,idempotency_key)');expect(sql).toContain('insert into messages');expect(sql).toContain('pg_advisory_xact_lock')})
