import{test,expect}from'@playwright/test'
import{readFileSync}from'node:fs'
const read=(path:string)=>readFileSync(path,'utf8')
test('authoritative web cancellation accepts every actionable invite state',()=>{const route=read('src/app/api/org/invites/route.ts');for(const status of['draft','pending','failed','pending_approval','awaiting_approval'])expect(route).toContain(`'${status}'`);expect(route).toContain("update({status:'canceled'})");expect(route).toContain("workspaceCan(authority.workspace,'manage_members')");expect(route).toContain(".eq('org_id',authoritativeOrgId)");expect(route).toContain("const resolvePostRequestUser=getMobileRequestUser")})
test('staff permissions offers individual and bulk cancellation without deleting history',()=>{const page=read('src/app/org/permissions/page.tsx'),route=read('src/app/api/org/invites/route.ts');expect(page).toContain('Cancel All Invitations');expect(page).toContain('Cancel invitation');expect(page).toContain("method:'DELETE'");expect(page).toContain('hidden duplicate attempts');expect(route).not.toContain("from('org_invites').delete")})
test('coach identity remains profile-first and team context stays secondary',()=>{for(const path of['src/app/coach/profile/page.tsx','src/app/coach/dashboard/page.tsx','src/app/coach/orgs-teams/page.tsx'])expect(read(path),path).toContain('full_name');const teams=read('src/app/coach/orgs-teams/page.tsx');expect(teams).toContain("coach?.full_name");expect(teams).toContain('team.name')})
test('web invitation surfaces send authoritative workspace and acting-role context',()=>{const helper=read('src/lib/clientWorkspaceRequest.ts');expect(helper).toContain("'X-Workspace-ID'");expect(helper).toContain("'X-Acting-Role'");expect(helper).toContain('Authorization: `Bearer ${accessToken}`');for(const path of['src/app/org/permissions/page.tsx','src/app/org/contacts/page.tsx','src/app/org/coaches/page.tsx','src/app/org/teams/page.tsx'])expect(read(path),path).toContain('organizationWorkspaceHeaders')})
test('mobile bearer authentication reaches DELETE before cookie and returns structured stages',()=>{const proxy=read('src/proxy.ts'),route=read('src/app/api/org/invites/route.ts'),auth=read('src/lib/mobileRequestAuth.ts'),fn=auth.slice(auth.indexOf('export const getMobileRequestUser'));expect(proxy).toContain('isMobileBearerAuthApiPath(pathname) && hasBearerAuthorization');expect(proxy).not.toContain("['GET', 'POST'].includes(req.method) && isMobileBearerAuthApiPath");expect(fn.indexOf("request.headers.get('authorization')")).toBeLessThan(fn.indexOf('createRouteHandlerClientCompat'));for(const field of["status: 'error'",'code, stage','request_id: requestId'])expect(route).toContain(field);expect(route).toContain("stage:'complete'");expect(route).toContain('cancel_all')})
test('required public app icons are present',()=>{for(const path of['public/favicon.ico','public/apple-touch-icon.png','public/apple-touch-icon-precomposed.png'])expect(()=>readFileSync(path)).not.toThrow()})
