import{test,expect}from'@playwright/test'
import{readFileSync}from'node:fs'
const read=(path:string)=>readFileSync(path,'utf8')

test('accepted active organization staff route from authoritative workspaces',()=>{const callback=read('src/app/auth/callback/route.ts'),resolver=read('src/lib/organizationStaffContext.ts');expect(callback).toContain(".eq('accepted_by',user.id)");expect(callback).toContain(".eq('status','accepted')");expect(callback).toContain("rpc('set_active_workspace'");for(const role of['owner','org_admin','club_admin','travel_admin','school_admin','athletic_director','program_director','team_manager','coach','assistant_coach'])expect(resolver).toContain(`'${role}'`);expect(resolver).toContain("nextPath:administrative?'/org':'/coach/dashboard'")})

test('combined organization roles prefer administrator authority over coach',()=>{const redirect=read('src/lib/roleRedirect.ts'),choices=read('src/lib/portalChoices.ts'),resolver=read('src/lib/organizationStaffContext.ts');expect(redirect.indexOf('const preferredOrgRole')).toBeLessThan(redirect.indexOf("normalizedRoles.includes('coach')"));expect(choices).toContain("['owner', 'org_admin'");expect(resolver.indexOf("'org_admin'")).toBeLessThan(resolver.indexOf("'program_director'"));expect(resolver.indexOf("'program_director'")).toBeLessThan(resolver.indexOf("'coach'"))})

test('organization-covered staff bypass onboarding only in the active organization workspace',()=>{const api=read('src/app/api/onboarding/route.ts'),coach=read('src/app/coach/dashboard/page.tsx'),athlete=read('src/app/athlete/dashboard/page.tsx');expect(api).toContain('organization_staff_covered');expect(api).toContain("active_role==='athlete'");expect(api).toContain('active_workspace_id');expect(coach).toContain('organization_staff_covered');expect(athlete).toContain('organization_staff_covered')})

test('browser account state is cleared on auth user replacement and onboarding keys are user scoped',()=>{const state=read('src/components/AccountScopedSessionState.tsx'),storage=read('src/lib/accountScopedStorage.ts'),layout=read('src/app/layout.tsx'),coach=read('src/app/coach/dashboard/page.tsx'),athlete=read('src/app/athlete/dashboard/page.tsx');expect(state).toContain('onAuthStateChange');expect(state).toContain('previous!==userId');expect(storage).toContain('ch_active_athlete_profile_id');expect(storage).toContain('athlete-marketplace-');expect(layout).toContain('<AccountScopedSessionState />');expect(coach).toContain("accountScopedStorageKey('ch_onboarding_coach_v1'");expect(athlete).toContain("accountScopedStorageKey('ch_onboarding_athlete_v1'")})

test('family profile discovery remains server-authoritative',()=>{const available=read('src/app/api/roles/available/route.ts'),active=read('src/app/api/workspaces/active/route.ts');expect(available).toContain("rpc('my_accessible_athlete_profiles')");expect(available).toContain("profile.owner_user_id === session.user.id");expect(active).toContain("rpc('my_accessible_athlete_profiles')");expect(active).toContain("return NextResponse.json({ error: 'That athlete profile is no longer available to your account.' }, { status: 403 })")})

test('canceled or removed staff cannot trigger the bypass',()=>{const resolver=read('src/lib/organizationStaffContext.ts'),callback=read('src/app/auth/callback/route.ts');expect(resolver).toContain("rpc('available_workspaces')");expect(callback).toContain(".eq('status','accepted')");expect(callback).not.toMatch(/pending.*resolveActiveOrganizationStaffContext/s)})
