import{test,expect}from'@playwright/test'
import{readFileSync}from'fs'
const read=(path:string)=>readFileSync(path,'utf8')
test('staff APIs use the authoritative authorization and synchronized mutation RPCs',()=>{const route=read('src/app/api/org/member-access/route.ts');expect(route).toContain("rpc('can_manage_org_staff'");expect(route).toContain("rpc('update_my_org_member_access'");expect(route).toContain('p_remove:false');expect(route).toContain('p_remove:true');expect(route).toContain("rpc('remove_my_org_coach'");expect(route).toContain("const STAFF_ROLES=['owner','org_admin','admin','program_director','team_manager','coach','assistant_coach']")})
test('legacy role and revoke endpoints use the authoritative mutation and never update membership state directly',()=>{for(const path of['src/app/api/org/memberships/role/route.ts','src/app/api/org/memberships/revoke/route.ts']){const route=read(path);expect(route).toContain("rpc('update_my_org_member_access'");expect(route).not.toContain("from('organization_memberships').update")};const revoke=read('src/app/api/org/memberships/revoke/route.ts');expect(revoke).toContain(".eq('status','suspended')")})
test('staff removal finalizes the legacy suspended marker without suspending the account',()=>{const route=read('src/app/api/org/member-access/route.ts');expect(route).toContain("from('organization_memberships').delete()");expect(route).toContain(".eq('status','suspended')");expect(route).not.toContain('updateUserById')})
test('staff UI distinguishes coach removal from complete access removal',()=>{const page=read('src/app/org/permissions/page.tsx');expect(page).toContain('Remove Coach');expect(page).toContain('Remove Staff Access');expect(page).toContain('Any owner, admin, or program-director access will be preserved.');expect(page).toContain('Their account and historical records will be preserved.');expect(page).toContain("method: 'DELETE'");expect(page).not.toContain("/api/org/memberships/role")})
test('custom roles normalize legacy permission arrays and use authoritative RPCs',()=>{const route=read('src/app/api/org/custom-roles/route.ts'),page=read('src/app/org/permissions/page.tsx');expect(route).toContain('Array.isArray(value)');expect(route).toContain("rpc('upsert_organization_role'");expect(route).toContain("rpc('assign_organization_role'");expect(route).toContain("from('organization_role_definitions')");expect(route).toContain("from('organization_role_assignments')");expect(page).toContain('manage_members:true,manage_schedule:true')})
test('coach management uses synchronized member-access API',()=>{const page=read('src/app/org/coaches/page.tsx');expect(page).toContain("fetch('/api/org/member-access'");expect(page).not.toMatch(/from\('organization_memberships'\)\s*\.update/ )})
