'use client'
import {useCallback,useEffect,useMemo,useState}from'react'
import Link from'next/link'
import {useParams}from'next/navigation'
import OrgSidebar from'@/components/OrgSidebar'
import LoadingState from'@/components/LoadingState'
import Toast from'@/components/Toast'
import {createSafeClientComponentClient as createClient}from'@/lib/supabaseHelpers'
import {getActiveOrganizationId}from'@/lib/clientOrganization'

const sources={program:{table:'programs',title:'name',assignment:'org_program_coaches',foreign:'program_id',rpc:'set_org_program_coaches',arg:'p_program_id',roster:'my_org_program_roster',rosterArg:'p_program_id'},tryout:{table:'org_tryouts',title:'title',assignment:'org_tryout_coaches',foreign:'tryout_id',rpc:'set_org_tryout_coaches',arg:'p_tryout_id',roster:'my_org_tryout_roster',rosterArg:'p_tryout_id'},training_package:{table:'org_training_packages',title:'name',assignment:'org_training_package_coaches',foreign:'package_id',rpc:'set_org_training_package_coaches',arg:'p_package_id',roster:null,rosterArg:null},training_session:{table:'org_training_sessions',title:'title',assignment:'org_training_session_coaches',foreign:'session_id',rpc:'set_org_training_session_coaches',arg:'p_session_id',roster:'my_org_training_session_roster',rosterArg:'p_session_id'},calendar_event:{table:'practice_plans',title:'title',assignment:'org_calendar_event_coaches',foreign:'event_id',rpc:'set_org_calendar_event_coaches',arg:'p_event_id',roster:'my_org_calendar_event_roster',rosterArg:'p_event_id'}}as const
type Kind=keyof typeof sources;type Coach={id:string;full_name:string|null};type Roster=Record<string,unknown>
export default function OfferingCoachDetail(){const params=useParams<{kind:string;id:string}>(),kind=params.kind as Kind,source=sources[kind],supabase=createClient();const[title,setTitle]=useState(''),[coaches,setCoaches]=useState<Coach[]>([]),[selected,setSelected]=useState<string[]>([]),[roster,setRoster]=useState<Roster[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[toast,setToast]=useState('');const names=useMemo(()=>new Map(coaches.map(c=>[c.id,c.full_name||'Coach'])),[coaches])
 const load=useCallback(async()=>{if(!source)return setLoading(false);setLoading(true);const orgId=await getActiveOrganizationId(supabase);if(!orgId)return setLoading(false);const[{data:item,error},{data:members},{data:links}]=await Promise.all([supabase.from(source.table).select(`id,${source.title}`).eq('id',params.id).eq('org_id',orgId).maybeSingle(),supabase.from('organization_memberships').select('user_id').eq('org_id',orgId).eq('status','active').in('role',['coach','assistant_coach','head_coach','program_director','org_admin','owner']),supabase.from(source.assignment).select('coach_id').eq(source.foreign,params.id)]);if(error||!item){setToast(error?.message||'Offering not found.');setLoading(false);return}const ids=Array.from(new Set((members||[]).map(m=>m.user_id))),{data:profiles}=ids.length?await supabase.from('profiles').select('id,full_name').in('id',ids):{data:[]};setTitle(String((item as Record<string,unknown>)[source.title]||'Offering'));setCoaches((profiles||[])as Coach[]);setSelected((links||[]).map(x=>x.coach_id));if(source.roster&&source.rosterArg){const{data,error:rosterError}=await supabase.rpc(source.roster,{[source.rosterArg]:params.id});if(!rosterError)setRoster((data||[])as Roster[])}setLoading(false)},[params.id,source,supabase]);useEffect(()=>{void load()},[load]);const toggle=(id:string)=>setSelected(rows=>rows.includes(id)?rows.filter(x=>x!==id):[...rows,id]);const save=async()=>{setToast('');setSaving(true);const{error}=await supabase.rpc(source.rpc,{[source.arg]:params.id,p_coach_ids:selected});setSaving(false);if(error)return setToast(error.message);setToast('Coach assignments saved.');void load()}
 if(!source)return <main className="p-8">Unsupported offering.</main>;return <div className="min-h-screen bg-[#f7f7f5]"><OrgSidebar/><main className="mx-auto max-w-5xl px-5 py-10 lg:pl-72"><Link href="/org/offering-coaches" className="text-sm text-gray-600">← Offerings</Link>{loading?<LoadingState/>:<><p className="mt-6 text-sm font-semibold uppercase tracking-wider text-[#b80f0a]">Offering details</p><h1 className="text-3xl font-bold">{title}</h1><section className="mt-8 rounded-2xl bg-white p-6 shadow-sm"><h2 className="text-xl font-semibold">Assigned coaches</h2><div className="mt-4 flex flex-wrap gap-2">{coaches.map(c=><button key={c.id} type="button" onClick={()=>toggle(c.id)} className={`rounded-full border px-3 py-2 text-sm ${selected.includes(c.id)?'border-[#b80f0a] bg-[#fff1ef] text-[#b80f0a]':''}`}>{selected.includes(c.id)?'✓ ':''}{names.get(c.id)}</button>)}</div><button disabled={saving} onClick={save} className="mt-5 rounded-lg bg-[#b80f0a] px-5 py-3 font-semibold text-white disabled:opacity-50">{saving?'Saving…':'Save assigned coaches'}</button></section>{source.roster&&<section className="mt-6 rounded-2xl bg-white p-6 shadow-sm"><div className="flex justify-between"><h2 className="text-xl font-semibold">Roster</h2><button onClick={()=>void load()} className="rounded-lg border px-3 py-2 text-sm">Refresh</button></div><div className="mt-4 divide-y">{roster.map((row,index)=><div key={String(row.booking_id||row.registration_id||row.athlete_id||index)} className="grid gap-2 py-3 text-sm sm:grid-cols-3"><strong>{String(row.athlete_name||'Athlete')}</strong><span>{String(row.booking_type||row.registration_status||row.roster_status||'Registered')}</span><span>{String(row.booked_at||row.registered_at||'')}</span></div>)}{!roster.length&&<p className="py-5 text-gray-500">No athletes yet.</p>}</div></section>}</>}{toast&&<Toast message={toast} onClose={()=>setToast('')}/>}</main></div>}
