import {NextResponse}from'next/server'
import {requireMobileOrgAuthority}from'@/lib/mobilePaymentApi'
import {supabaseAdmin}from'@/lib/supabaseAdmin'
import {parseUuid}from'@/lib/uuid'
import {mobileContractError}from'@/lib/mobileApiContract'
export async function GET(request:Request,{params}:{params:Promise<{id:string}>}){const auth=await requireMobileOrgAuthority(request,'manage_schedule');if('response'in auth)return auth.response;const id=parseUuid((await params).id);if(!id)return mobileContractError('occurrence_invalid','Choose a valid occurrence.',422,false)
 const{data:session}=await supabaseAdmin.from('org_training_sessions').select('*').eq('id',id).eq('org_id',auth.orgId).maybeSingle();if(!session)return mobileContractError('occurrence_unavailable','This occurrence is unavailable.',404,false)
 const{data:bookings,error}=await supabaseAdmin.from('org_training_session_bookings').select('*').eq('session_id',id).order('booked_at');if(error)return mobileContractError('roster_unavailable','The occurrence roster is temporarily unavailable.',503,true)
 const athleteIds=(bookings||[]).map(b=>b.athlete_id),payerIds=(bookings||[]).map(b=>b.booked_by),[{data:athletes},{data:parents},{data:attendance}]=await Promise.all([athleteIds.length?supabaseAdmin.from('athlete_profiles').select('id,full_name,owner_user_id,auth_user_id').in('id',athleteIds):Promise.resolve({data:[]}),payerIds.length?supabaseAdmin.from('profiles').select('id,full_name').in('id',payerIds):Promise.resolve({data:[]}),supabaseAdmin.from('session_attendance').select('athlete_id,status,marked_at').eq('session_id',id)])
 const am=new Map((athletes||[]).map(a=>[a.id,a])),pm=new Map((parents||[]).map(p=>[p.id,p])),tm=new Map((attendance||[]).map(a=>[a.athlete_id,a])),active=(bookings||[]).filter(b=>['pending_payment','reserved','attended','no_show'].includes(b.status))
 return NextResponse.json({occurrence:{...session,total_booked:active.length,capacity_remaining:Math.max(0,Number(session.capacity)-active.length)},roster:(bookings||[]).map(b=>{const a=am.get(b.athlete_id),t=tm.get(b.athlete_id);return{booking_id:b.id,athlete_profile_id:b.athlete_id,athlete_name:a?.full_name||'Athlete',parent_guardian:{user_id:b.booked_by,full_name:pm.get(b.booked_by)?.full_name||null},booking_status:b.status,payment_status:b.booking_type==='credit'?'credit_applied':b.status==='pending_payment'?'pending':'paid',booked_at:b.booked_at,attendance_status:t?.status||null,attendance_marked_at:t?.marked_at||null}})})}
