'use client'

import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react'

type Task = { id:string; title:string; details:string|null; category:string; priority:string; status:string; due_at:string|null; assigned_to:string|null }
type Assignee = { id:string; full_name:string|null; email:string|null }

export default function OrgTasksPage() {
  const [tasks,setTasks]=useState<Task[]>([]), [assignees,setAssignees]=useState<Assignee[]>([])
  const [canManage,setCanManage]=useState(false), [loading,setLoading]=useState(true), [message,setMessage]=useState('')
  const [filter,setFilter]=useState('open'), [query,setQuery]=useState(''), [showCreate,setShowCreate]=useState(false)
  const [form,setForm]=useState({title:'',details:'',category:'general',priority:'normal',due_at:'',assigned_to:''})
  const load=useCallback(async()=>{setLoading(true);setMessage('');try{const response=await fetch('/api/org/tasks',{cache:'no-store'});const body=await response.json();if(!response.ok)throw new Error(body.error||'Unable to load tasks');setTasks(body.tasks||[]);setAssignees(body.assignees||[]);setCanManage(Boolean(body.can_manage))}catch(error){setMessage(error instanceof Error?error.message:'Unable to load tasks')}finally{setLoading(false)}},[])
  useEffect(()=>{void load()},[load])
  const visible=useMemo(()=>tasks.filter(task=>{
    const status=filter==='all'||(filter==='open'?!['completed','cancelled'].includes(task.status):task.status==='completed')
    const search=!query||`${task.title} ${task.details||''}`.toLowerCase().includes(query.toLowerCase())
    return status&&search
  }).sort((a,b)=>({urgent:4,high:3,normal:2,low:1}[b.priority]||0)-({urgent:4,high:3,normal:2,low:1}[a.priority]||0)),[tasks,filter,query])
  async function create(event:FormEvent){event.preventDefault();setMessage('');const response=await fetch('/api/org/tasks',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...form,due_at:form.due_at?new Date(form.due_at).toISOString():null,assigned_to:form.assigned_to||null})});const body=await response.json();if(!response.ok){setMessage(body.error||'Unable to create task');return}setForm({title:'',details:'',category:'general',priority:'normal',due_at:'',assigned_to:''});setShowCreate(false);await load()}
  async function toggle(task:Task){const response=await fetch('/api/org/tasks',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id:task.id,completed:task.status!=='completed'})});if(response.ok)await load();else setMessage((await response.json()).error||'Unable to update task')}
  async function remove(id:string){if(!window.confirm('Delete this task?'))return;const response=await fetch(`/api/org/tasks?id=${encodeURIComponent(id)}`,{method:'DELETE'});if(response.ok)await load();else setMessage((await response.json()).error||'Unable to delete task')}
  const name=(id:string|null)=>assignees.find(item=>item.id===id)?.full_name||assignees.find(item=>item.id===id)?.email||''
  return <main className="page-shell"><div className="mx-auto max-w-6xl space-y-6">
    <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Organization operations</p><h1 className="display-title">Tasks</h1><p className="mt-2 text-[#555]">Create, assign, complete, and reopen the same organization tasks used in the mobile app.</p></div>{canManage&&<button className="btn-primary" onClick={()=>setShowCreate(value=>!value)}>{showCreate?'Cancel':'Create task'}</button>}</header>
    {message&&<div className="rounded-2xl border border-red-300 bg-red-50 p-4 text-red-800">{message}</div>}
    {showCreate&&<form onSubmit={create} className="glass-card grid gap-4 p-6 md:grid-cols-2"><label className="md:col-span-2">Task title<input required maxLength={160} className="input mt-2 w-full" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label className="md:col-span-2">Details<textarea className="input mt-2 w-full" value={form.details} onChange={e=>setForm({...form,details:e.target.value})}/></label><label>Category<select className="input mt-2 w-full" value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{['general','roster','schedule','payments','documents','compliance','operations'].map(value=><option key={value}>{value}</option>)}</select></label><label>Priority<select className="input mt-2 w-full" value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}>{['low','normal','high','urgent'].map(value=><option key={value}>{value}</option>)}</select></label><label>Due date<input type="datetime-local" className="input mt-2 w-full" value={form.due_at} onChange={e=>setForm({...form,due_at:e.target.value})}/></label><label>Assign to<select className="input mt-2 w-full" value={form.assigned_to} onChange={e=>setForm({...form,assigned_to:e.target.value})}><option value="">Unassigned</option>{assignees.map(person=><option key={person.id} value={person.id}>{person.full_name||person.email||'Organization member'}</option>)}</select></label><button className="btn-primary md:col-span-2" type="submit">Save task</button></form>}
    <section className="glass-card p-5"><div className="flex flex-wrap gap-3"><input aria-label="Search tasks" placeholder="Search tasks" className="input min-w-64 flex-1" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Task status" className="input" value={filter} onChange={e=>setFilter(e.target.value)}><option value="open">Open</option><option value="completed">Completed</option><option value="all">All</option></select></div></section>
    {loading?<div className="glass-card p-8">Loading tasks…</div>:visible.length===0?<div className="glass-card p-8">No matching tasks.</div>:<div className="space-y-3">{visible.map(task=><article key={task.id} className="glass-card flex flex-wrap items-start gap-4 p-5"><button aria-label={task.status==='completed'?'Reopen task':'Complete task'} onClick={()=>void toggle(task)} className="mt-1 h-6 w-6 rounded-full border border-[#222] text-sm">{task.status==='completed'?'✓':''}</button><div className="min-w-0 flex-1"><h2 className={`text-lg font-bold ${task.status==='completed'?'line-through':''}`}>{task.title}</h2>{task.details&&<p className="mt-1 text-[#555]">{task.details}</p>}<div className="mt-3 flex flex-wrap gap-2 text-xs uppercase tracking-wide"><span className="rounded-full bg-[#eee] px-3 py-1">{task.priority}</span><span className="rounded-full bg-[#eee] px-3 py-1">{task.category}</span>{task.due_at&&<span className="rounded-full bg-[#eee] px-3 py-1">Due {new Date(task.due_at).toLocaleString()}</span>}{name(task.assigned_to)&&<span className="rounded-full bg-[#eee] px-3 py-1">{name(task.assigned_to)}</span>}</div></div>{canManage&&<button className="btn-secondary" onClick={()=>void remove(task.id)}>Delete</button>}</article>)}</div>}
  </div></main>
}
