'use client'
import { FormEvent, useCallback, useEffect, useState } from 'react'
import OrgSidebar from '@/components/OrgSidebar'
import EmptyState from '@/components/EmptyState'
import LoadingState from '@/components/LoadingState'

type Coach = { id: string; name: string }
type RequestRow = { id:string;coach_name:string;title:string;description?:string|null;document_type:string;due_at?:string|null;status:string;review_note?:string|null;submission?:{filename:string;note?:string|null;download_url?:string|null}|null }

export default function OrgCoachDocumentsPage(){
  const [requests,setRequests]=useState<RequestRow[]>([]);const[coaches,setCoaches]=useState<Coach[]>([]);const[loading,setLoading]=useState(true);const[notice,setNotice]=useState('');
  const load=useCallback(async()=>{setLoading(true);const r=await fetch('/api/org/coach-documents',{cache:'no-store'});const p=await r.json().catch(()=>({}));if(!r.ok)setNotice(p.error||'Unable to load requests.');else{setRequests(p.requests||[]);setCoaches(p.coaches||[])}setLoading(false)},[])
  useEffect(()=>{void load()},[load])
  const create=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=new FormData(e.currentTarget);const r=await fetch('/api/org/coach-documents',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(form))});const p=await r.json().catch(()=>({}));if(!r.ok)setNotice(p.error||'Unable to create request.');else{e.currentTarget.reset();setNotice('Document request sent.');await load()}}
  const review=async(id:string,decision:string)=>{const note=window.prompt(decision==='approved'?'Approval note (optional)':'What needs to be replaced?')||'';const r=await fetch('/api/org/coach-documents',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({request_id:id,decision,note})});const p=await r.json().catch(()=>({}));if(!r.ok)setNotice(p.error||'Unable to review document.');else{setNotice(`Document ${decision}.`);await load()}}
  return <main className="page-shell"><div className="relative z-10 px-4 py-6 sm:px-6 sm:py-10"><div className="grid gap-6 lg:grid-cols-[220px_minmax(0,1fr)]"><OrgSidebar/><section><p className="text-xs uppercase tracking-[.3em] text-[#b80f0a]">Organization portal</p><h1 className="display text-3xl font-semibold">Coach documents</h1><p className="mt-2 text-sm text-[#4a4a4a]">Request, receive, and review certifications and other staff paperwork.</p>{notice&&<p className="mt-4 rounded-xl border bg-white p-3 text-sm">{notice}</p>}
  <form onSubmit={create} className="glass-card mt-6 grid gap-3 p-5 sm:grid-cols-2"><h2 className="text-lg font-semibold sm:col-span-2">New request</h2><select required name="coach_id" className="rounded-xl border p-3"><option value="">Select coach</option>{coaches.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select name="document_type" className="rounded-xl border p-3">{['certification','background_check','cpr_first_aid','insurance','contract','other'].map(v=><option key={v} value={v}>{v.replaceAll('_',' ')}</option>)}</select><input required name="title" maxLength={160} placeholder="Document title" className="rounded-xl border p-3 sm:col-span-2"/><textarea name="description" maxLength={4000} placeholder="Instructions" className="rounded-xl border p-3 sm:col-span-2"/><input name="due_at" type="date" className="rounded-xl border p-3"/><button className="w-fit rounded-full bg-[#191919] px-5 py-2.5 font-semibold text-white">Send request</button></form>
  {loading?<LoadingState className="mt-6" label="Loading coach documents…"/>:requests.length===0?<EmptyState className="mt-6" title="No coach document requests" description="Create a request when staff paperwork is needed."/>:<div className="mt-6 space-y-4">{requests.map(x=><article key={x.id} className="glass-card border border-[#191919] bg-white p-5"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-semibold">{x.title}</h2><p className="text-sm text-[#6b5f55]">{x.coach_name} · {x.document_type.replaceAll('_',' ')}</p></div><span className="rounded-full border px-3 py-1 text-xs font-semibold capitalize">{x.status}</span></div>{x.description&&<p className="mt-3 text-sm">{x.description}</p>}{x.submission&&<div className="mt-3 rounded-xl border p-3 text-sm"><p className="font-semibold">{x.submission.filename}</p>{x.submission.download_url&&<a className="underline" href={x.submission.download_url}>Review document</a>}</div>}{x.status==='submitted'&&<div className="mt-4 flex gap-2"><button onClick={()=>void review(x.id,'approved')} className="rounded-full bg-[#191919] px-4 py-2 text-sm font-semibold text-white">Approve</button><button onClick={()=>void review(x.id,'rejected')} className="rounded-full border px-4 py-2 text-sm font-semibold">Request replacement</button></div>}</article>)}</div>}
  </section></div></div></main>}
