'use client'

import { useCallback, useEffect, useState } from 'react'
import AdminSidebar from '@/components/AdminSidebar'
import LoadingState from '@/components/LoadingState'

export default function WorkspaceReconciliationPage() {
  const [items,setItems]=useState<any[]>([]),[workspaces,setWorkspaces]=useState<any[]>([]),[loading,setLoading]=useState(true),[notice,setNotice]=useState(''),[query,setQuery]=useState('')
  const [assignments,setAssignments]=useState<Record<string,string>>({})
  const load=useCallback(async()=>{setLoading(true);const r=await fetch(`/api/admin/workspace-reconciliation?query=${encodeURIComponent(query)}`,{cache:'no-store'}),p=await r.json().catch(()=>({}));setItems(r.ok?p.items||[]:[]);setWorkspaces(r.ok?p.workspaces||[]:[]);setNotice(r.ok?'':p.error||'Unable to load queue.');setLoading(false)},[query])
  useEffect(()=>{void load()},[load])
  const assign=async(item:any)=>{const workspaceId=assignments[`${item.table_name}:${item.id}`];if(!workspaceId)return;const reason=window.prompt('Why does this record belong to this workspace?')?.trim();if(!reason)return;const r=await fetch(`/api/admin/workspaces/${workspaceId}/actions`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'assign_reconciliation_record',table_name:item.table_name,record_id:item.id,reason})}),p=await r.json().catch(()=>({}));setNotice(r.ok?'Record assigned with an audit event.':p.error||'Assignment failed.');if(r.ok)await load()}
  return <main className="page-shell"><div className="relative z-10 px-6 py-10"><div className="grid items-start gap-6 lg:grid-cols-[200px_1fr]"><AdminSidebar/><section className="min-w-0"><p className="text-xs uppercase tracking-[0.3em] text-[#6b5f55]">Workspace authority</p><h1 className="display text-3xl font-semibold">Reconciliation queue</h1><p className="mt-2 text-sm text-[#6b5f55]">Legacy records that could not be assigned safely. Every assignment requires a reason and creates an audit event.</p><form className="mt-5 flex gap-2" onSubmit={(e)=>{e.preventDefault();void load()}}><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder="Search table or record ID" className="flex-1 rounded-2xl border bg-white px-4 py-2"/><button className="rounded-2xl bg-[#191919] px-4 py-2 text-white">Search</button></form>{notice?<p className="mt-4 rounded-xl border bg-white p-3 text-sm">{notice}</p>:null}{loading?<LoadingState label="Loading reconciliation queue…"/>:<div className="mt-5 space-y-3">{items.map(item=>{const key=`${item.table_name}:${item.id}`;return <div key={key} className="rounded-2xl border bg-white p-4"><p className="font-semibold">{item.table_name}</p><p className="break-all text-xs text-[#6b5f55]">{item.id}</p><div className="mt-3 flex flex-wrap gap-2"><select value={assignments[key]||''} onChange={(e)=>setAssignments(v=>({...v,[key]:e.target.value}))} className="min-w-[260px] rounded-xl border px-3 py-2 text-sm"><option value="">Choose verified workspace</option>{workspaces.map(w=><option key={w.id} value={w.id}>{w.display_name} ({w.workspace_type})</option>)}</select><button onClick={()=>void assign(item)} className="rounded-xl bg-[#191919] px-4 py-2 text-sm font-semibold text-white">Assign</button></div></div>})}</div>}</section></div></div></main>
}
