'use client'

import { useCallback, useEffect, useState } from 'react'

type Report = { id:string; reporter_name:string; reported_user_name:string|null; content_type:string; reason:string; details:string|null; status:string; admin_notes:string|null; created_at:string }
const statuses = ['open','in_review','resolved','dismissed','all']

export default function AdminModerationPage() {
  const [reports,setReports]=useState<Report[]>([]),[status,setStatus]=useState('open'),[page,setPage]=useState(1),[pages,setPages]=useState(1)
  const [loading,setLoading]=useState(true),[notice,setNotice]=useState(''),[notes,setNotes]=useState<Record<string,string>>({})
  const load=useCallback(async()=>{setLoading(true);setNotice('');const response=await fetch(`/api/admin/moderation?status=${status}&page=${page}`,{cache:'no-store'}).catch(()=>null);const payload=await response?.json().catch(()=>null);if(!response?.ok){setNotice(payload?.error||'Unable to load content reports.')}else{setReports(payload.reports||[]);setPages(payload.total_pages||1)}setLoading(false)},[page,status])
  useEffect(()=>{void load()},[load])
  const update=async(id:string,nextStatus:string)=>{setNotice('');const response=await fetch('/api/admin/moderation',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,status:nextStatus,admin_notes:notes[id]||''})});const payload=await response.json().catch(()=>null);if(!response.ok){setNotice(payload?.error||'Unable to update this report.');return}await load()}
  return <main className="page-shell min-h-screen"><div className="mx-auto max-w-7xl px-5 py-10"><p className="public-kicker">Superadmin</p><h1 className="mt-2 text-3xl font-semibold">Content moderation</h1><p className="mt-2 text-neutral-600">Review the same reports submitted from mobile and web.</p>
    <div className="mt-6 flex flex-wrap gap-2">{statuses.map(value=><button key={value} type="button" onClick={()=>{setStatus(value);setPage(1)}} className={`rounded-full px-4 py-2 text-sm font-semibold ${status===value?'bg-[#191919] text-white':'border bg-white'}`}>{value.replace('_',' ')}</button>)}</div>
    {notice?<p role="alert" className="mt-5 rounded-xl border border-red-300 bg-red-50 p-4 text-red-800">{notice}</p>:null}
    {loading?<p className="mt-8">Loading reports…</p>:<div className="mt-6 space-y-4">{reports.length===0?<p className="rounded-2xl border bg-white p-6">No reports match this filter.</p>:reports.map(report=><article key={report.id} className="rounded-2xl border bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wide text-red-700">{report.content_type} · {report.status}</p><h2 className="mt-1 text-xl font-semibold">{report.reason}</h2><p className="mt-1 text-sm text-neutral-600">Reported by {report.reporter_name}{report.reported_user_name?` · Against ${report.reported_user_name}`:''} · {new Date(report.created_at).toLocaleString()}</p></div></div><p className="mt-4 whitespace-pre-wrap">{report.details||'No additional details supplied.'}</p><label className="mt-4 grid gap-1 text-sm font-semibold">Internal notes<textarea className="min-h-24 rounded-xl border p-3 font-normal" value={notes[report.id]??report.admin_notes??''} onChange={event=>setNotes(current=>({...current,[report.id]:event.target.value}))}/></label><div className="mt-4 flex flex-wrap gap-2"><button type="button" onClick={()=>void update(report.id,'in_review')} className="rounded-full border px-4 py-2 font-semibold">Mark in review</button><button type="button" onClick={()=>void update(report.id,'resolved')} className="rounded-full bg-[#191919] px-4 py-2 font-semibold text-white">Resolve</button><button type="button" onClick={()=>void update(report.id,'dismissed')} className="rounded-full border px-4 py-2 font-semibold">Dismiss</button></div></article>)}</div>}
    <nav aria-label="Moderation pages" className="mt-6 flex items-center justify-between"><button type="button" disabled={page<=1} onClick={()=>setPage(value=>value-1)} className="rounded-full border bg-white px-4 py-2 disabled:opacity-40">Previous</button><span>Page {page} of {pages}</span><button type="button" disabled={page>=pages} onClick={()=>setPage(value=>value+1)} className="rounded-full border bg-white px-4 py-2 disabled:opacity-40">Next</button></nav>
  </div></main>
}
