'use client'

import {useCallback,useEffect,useState} from 'react'
import CoachSidebar from '@/components/CoachSidebar'
import LoadingState from '@/components/LoadingState'
import Toast from '@/components/Toast'
import {createSafeClientComponentClient as createClient} from '@/lib/supabaseHelpers'

type Assignment={id:string;kind:'program'|'tryout'|'training_package'|'training_session'|'calendar_event';title:string;when:string|null;location:string|null;status:string|null;rosterRpc:string|null;rosterArg:string|null}
type RosterRow={registration_id?:string;booking_id?:string;invitation_id?:string;athlete_name:string;registration_status?:string;booking_status?:string;invitation_status?:string;rsvp_status?:string;registered_at?:string;booked_at?:string;invited_at?:string;booking_type?:string}
const configs=[
 {kind:'program',join:'org_program_coaches',fk:'program_id',table:'programs',select:'id,name,start_date,location,status',title:'name',when:'start_date',rosterRpc:'my_org_program_roster',rosterArg:'p_program_id'},
 {kind:'tryout',join:'org_tryout_coaches',fk:'tryout_id',table:'org_tryouts',select:'id,title,tryout_date,location,status',title:'title',when:'tryout_date',rosterRpc:'my_org_tryout_roster',rosterArg:'p_tryout_id'},
 {kind:'training_package',join:'org_training_package_coaches',fk:'package_id',table:'org_training_packages',select:'id,name,status,location',title:'name',when:null,rosterRpc:null,rosterArg:null},
 {kind:'training_session',join:'org_training_session_coaches',fk:'session_id',table:'org_training_sessions',select:'id,title,starts_at,location,status',title:'title',when:'starts_at',rosterRpc:'my_org_training_session_roster',rosterArg:'p_session_id'},
 {kind:'calendar_event',join:'org_calendar_event_coaches',fk:'event_id',table:'practice_plans',select:'id,title,start_time,location,status',title:'title',when:'start_time',rosterRpc:'my_org_calendar_event_roster',rosterArg:'p_event_id'},
] as const
const label=(kind:string)=>kind.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())

export default function OrganizationAssignmentsPage(){
 const supabase=createClient(),[loading,setLoading]=useState(true),[items,setItems]=useState<Assignment[]>([]),[roster,setRoster]=useState<RosterRow[]|null>(null),[rosterTitle,setRosterTitle]=useState(''),[toast,setToast]=useState('')
 const load=useCallback(async()=>{setLoading(true);const{data:userData}=await supabase.auth.getUser(),userId=userData.user?.id;if(!userId){setLoading(false);return}const groups=await Promise.all(configs.map(async config=>{const{data:links}=await supabase.from(config.join).select(config.fk).eq('coach_id',userId),ids=(links||[]).map((x:any)=>x[config.fk]);if(!ids.length)return[];const{data:rows}=await supabase.from(config.table).select(config.select).in('id',ids);return(rows||[]).map((row:any)=>({id:row.id,kind:config.kind,title:row[config.title]||label(config.kind),when:config.when?row[config.when]||null:null,location:row.location||null,status:row.status||null,rosterRpc:config.rosterRpc,rosterArg:config.rosterArg}))}));setItems((groups.flat()as Assignment[]).sort((a,b)=>new Date(a.when||'2999-12-31').getTime()-new Date(b.when||'2999-12-31').getTime()));setLoading(false)},[supabase])
 useEffect(()=>{void load()},[load])
 const showRoster=async(item:Assignment)=>{if(!item.rosterRpc||!item.rosterArg)return;const{data,error}=await supabase.rpc(item.rosterRpc,{[item.rosterArg]:item.id});if(error)return setToast(error.message);setRosterTitle(item.title);setRoster((data||[])as RosterRow[])}
 return <main className="page-shell"><div className="relative z-10 px-4 py-6 sm:px-6 sm:py-10"><CoachSidebar/><section className="mx-auto max-w-5xl"><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#b80f0a]">Coach workspace</p><div className="flex items-end justify-between"><div><h1 className="mt-1 text-3xl font-bold">My Organization Assignments</h1><p className="mt-2 text-gray-600">Programs, tryouts, packages, practices, games, and paid sessions assigned to you.</p></div><button onClick={()=>void load()} className="rounded-lg border px-4 py-2">Refresh</button></div>{loading?<div className="mt-8"><LoadingState/></div>:<div className="mt-8 grid gap-4 md:grid-cols-2">{items.map(item=><article key={`${item.kind}:${item.id}`} className="rounded-2xl border bg-white p-5"><p className="text-xs font-semibold uppercase tracking-wider text-gray-500">{label(item.kind)}</p><h2 className="mt-1 text-xl font-semibold">{item.title}</h2><p className="mt-2 text-sm text-gray-600">{item.when?new Date(item.when).toLocaleString():'Ongoing'}{item.location?` · ${item.location}`:''}{item.status?` · ${item.status}`:''}</p>{item.rosterRpc?<button onClick={()=>void showRoster(item)} className="mt-4 rounded-lg border px-4 py-2 text-sm font-semibold">View roster</button>:null}</article>)}{!items.length?<p className="rounded-2xl bg-white p-8 text-center text-gray-500 md:col-span-2">No organization assignments yet.</p>:null}</div>}</section></div>{roster?<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4" onClick={()=>setRoster(null)}><section className="max-h-[80vh] w-full max-w-2xl overflow-auto rounded-2xl bg-white p-6" onClick={event=>event.stopPropagation()}><div className="flex justify-between"><h2 className="text-xl font-semibold">{rosterTitle} roster</h2><button onClick={()=>setRoster(null)}>Close</button></div><div className="mt-4 divide-y">{roster.map((row,index)=><div key={row.registration_id||row.booking_id||row.invitation_id||index} className="grid grid-cols-2 gap-2 py-3 text-sm"><strong>{row.athlete_name}</strong><span>{row.booking_type||'Invitation'}</span><span>{row.registration_status||row.booking_status||row.rsvp_status||row.invitation_status}</span><span>{new Date(row.registered_at||row.booked_at||row.invited_at||'').toLocaleString()}</span></div>)}{!roster.length?<p className="py-6 text-gray-500">No registrations yet.</p>:null}</div></section></div>:null}{toast?<Toast message={toast} onClose={()=>setToast('')}/>:null}</main>
}
