'use client'

import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'

type PaymentView={organization_name:string;logo_url:string|null;athlete:string|null;payer_verified:boolean;fee_description:string;base_amount_cents:number;service_fee_cents:number;total_cents:number;service_fee_label:string;due_at:string|null;payment_status:string;expires_at:string;cancellation_terms:string;refund_terms:string}
const money=(cents:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(cents/100)

export default function PaymentLinkClient({token}:{token:string}){
  const router=useRouter(),[data,setData]=useState<PaymentView|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[starting,setStarting]=useState(false)
  useEffect(()=>{fetch(`/api/pay/${encodeURIComponent(token)}`,{cache:'no-store'}).then(async r=>{const p=await r.json();if(!r.ok)throw new Error(p?.error?.message||'This payment link is unavailable.');return p}).then(setData).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[token])
  const checkout=async()=>{setStarting(true);setError('');const r=await fetch(`/api/pay/${encodeURIComponent(token)}`,{method:'POST'});const p=await r.json().catch(()=>({}));if(!r.ok){setError(p?.error?.message||'Unable to start checkout.');setStarting(false);return}window.location.assign(p.checkout_url)}
  if(loading)return <main className="grid min-h-screen place-items-center bg-[#f4f3f1] p-5"><p className="text-sm text-[#666]">Loading secure payment…</p></main>
  if(error&&!data)return <main className="grid min-h-screen place-items-center bg-[#f4f3f1] p-5"><section className="w-full max-w-lg rounded-3xl bg-white p-7 shadow-sm"><p className="text-xs font-bold uppercase tracking-[.22em] text-[#b80f0a]">Coaches Hive</p><h1 className="mt-3 text-2xl font-semibold">Payment link unavailable</h1><p className="mt-3 text-[#5f5f5f]">{error}</p></section></main>
  if(!data)return null
  return <main className="min-h-screen bg-[#f4f3f1] px-4 py-8 text-[#191919] sm:py-12"><section className="mx-auto w-full max-w-xl overflow-hidden rounded-[2rem] border border-black/10 bg-white shadow-sm"><header className="bg-[#c40f0a] px-6 py-7 text-white sm:px-8"><p className="text-sm font-black tracking-[.18em]">COACHES<span className="text-black">HIVE</span></p><div className="mt-5 flex items-center gap-3">{data.logo_url?<img src={data.logo_url} alt="" className="h-12 w-12 rounded-full bg-white object-cover"/>:null}<div><p className="text-sm text-white/80">Secure payment for</p><h1 className="mt-1 text-2xl font-semibold">{data.organization_name}</h1></div></div></header><div className="space-y-6 p-6 sm:p-8"><div><p className="text-sm text-[#666]">Fee</p><h2 className="mt-1 text-xl font-semibold">{data.fee_description}</h2>{data.payer_verified&&data.athlete?<p className="mt-2 text-sm text-[#555]">Athlete: <strong>{data.athlete}</strong></p>:<p className="mt-2 rounded-2xl bg-amber-50 p-3 text-sm text-amber-900">Sign in with the invited payer account to reveal athlete details and continue.</p>}{data.due_at?<p className="mt-2 text-sm text-[#666]">Due {new Date(data.due_at).toLocaleDateString()}</p>:null}</div><div className="rounded-2xl border bg-[#fafafa] p-5"><div className="flex justify-between py-2"><span>Base amount</span><strong>{money(data.base_amount_cents)}</strong></div><div className="flex justify-between border-t py-3 text-sm"><span>{data.service_fee_label}</span><strong>{money(data.service_fee_cents)}</strong></div><div className="flex justify-between border-t pt-4 text-lg"><strong>Total</strong><strong>{money(data.total_cents)}</strong></div></div><div className="space-y-2 text-xs leading-5 text-[#666]"><p>{data.cancellation_terms}</p><p>{data.refund_terms}</p></div>{data.payer_verified?<button disabled={starting} onClick={checkout} className="w-full rounded-2xl bg-[#c40f0a] px-5 py-4 text-base font-bold text-white disabled:opacity-60">{starting?'Opening secure checkout…':'Continue to secure checkout'}</button>:<button onClick={()=>router.push(`/login?next=${encodeURIComponent(`/pay/${token}`)}`)} className="w-full rounded-2xl bg-[#c40f0a] px-5 py-4 text-base font-bold text-white">Sign in to continue</button>}{error?<p className="text-sm font-medium text-red-700">{error}</p>:null}<p className="text-center text-xs text-[#777]">Card and ACH payments are processed securely by Stripe.</p></div></section></main>
}
