import { ORGANIZATION_AGREEMENT_EFFECTIVE_DATE, ORGANIZATION_AGREEMENT_VERSION } from '@/lib/legalAgreements'

const items = [
  ['Parties, roles, and scope', 'This addendum forms part of the Organization Terms between the organization and Coaches Hive. For organization-submitted personal data, the organization determines the permitted business purposes and Coaches Hive acts as its service provider or processor except when Coaches Hive processes information for its own billing, security, fraud-prevention, legal, or direct-user obligations. Processing continues for the subscription term and any limited return, backup, legal-hold, or deletion period.'],
  ['Instructions and permitted use', 'Coaches Hive will process organization data only on documented instructions embodied in the agreement, product configuration, support requests, and authorized use of the service; to provide, secure, support, and maintain the service; or as required by law. Coaches Hive will not sell organization data or use it for targeted advertising. If an instruction appears unlawful, Coaches Hive may suspend it and notify the organization where legally permitted.'],
  ['Data and people covered', 'Organization account data, authorized-user records, athlete and guardian information, registrations, rosters, schedules, attendance, communications, waivers, uploaded documents, support data, device and audit records, and payment-related records may be processed. Data subjects may include administrators, staff, coaches, volunteers, athletes, parents, guardians, customers, and prospective participants.'],
  ['Confidentiality and security', 'Coaches Hive will use personnel and contractors subject to confidentiality duties and maintain reasonable administrative, technical, and organizational safeguards appropriate to the nature of the data and risk. Safeguards include access controls, authentication, transmission protection, logging, vulnerability and dependency management, backup controls, incident response, and least-privilege access where applicable. No service can guarantee absolute security.'],
  ['Minors and children', 'The organization must provide required notices and have lawful authority before submitting minor information. This allocation does not transfer or replace any direct notice, consent, data-minimization, security, or deletion duty that applies independently to Coaches Hive. The Children’s Privacy Notice governs covered information about children under 13.'],
  ['Service providers', 'The organization gives general authorization for Coaches Hive to use service providers for hosting, authentication, payments, email, monitoring, analytics, customer support, and security. Coaches Hive will require those providers to protect personal data consistently with their assigned services and remains responsible for its contractual obligations. Organizations may request notice of material provider changes and raise a reasonable data-protection objection.'],
  ['Security incidents', 'After confirming unauthorized access to or acquisition, disclosure, alteration, loss, or destruction of organization data, Coaches Hive will notify affected organizations without unreasonable delay and provide available information reasonably needed for the organization’s legal obligations. Notice may be delayed when required by law enforcement or necessary to avoid compromising an investigation. Notification is not an admission of fault.'],
  ['Individual requests and compliance assistance', 'Taking account of the nature of processing, Coaches Hive will provide reasonable assistance with access, correction, deletion, restriction, export, consent withdrawal, regulator inquiries, impact assessments, and other legally required requests involving organization data. The organization remains responsible for determining how to respond when it controls the data.'],
  ['Return, deletion, and retention', 'Organizations should export needed records before access ends. Following termination, Coaches Hive will delete or de-identify organization data within the period stated in the service terms unless return is requested, law requires retention, a legal hold applies, or secure backups cycle out later. Any retained data remains protected and may be used only for the reason retained.'],
  ['Audit information', 'On reasonable written request, Coaches Hive will provide information reasonably necessary to demonstrate compliance, such as relevant policies, summaries, certifications, or security questionnaires. Any inspection must protect other customers, confidential information, and system security, avoid unreasonable disruption, and be limited to what applicable law requires.'],
  ['International and U.S. state requirements', 'If data is transferred across national borders, the parties will use a legally recognized transfer mechanism where required. To the extent a U.S. state privacy law applies, Coaches Hive will act as a service provider or processor for organization data, process it for the limited purposes in the agreement, provide the same level of privacy protection required by applicable law, and notify the organization if it can no longer meet those obligations.'],
  ['Schools and FERPA', 'A school or district may require a separately signed student-data, FERPA, or state-specific addendum. A signed school-specific agreement or order form controls over this standard addendum only for the conflicting subject. Coaches Hive will not use education records for unauthorized purposes or redisclose them except as permitted by the governing agreement and law.'],
  ['Order of precedence and liability', 'This addendum controls over conflicting general privacy language for organization data. A signed order form or school addendum may expressly modify it. The Terms of Service provisions concerning disclaimers, liability, disputes, and termination apply to this addendum unless a signed agreement expressly states otherwise.'],
]

export default function DataProcessingAddendumPage() {
  return <main className="page-shell public-page"><div className="relative z-10 mx-auto max-w-4xl px-6 py-16">
    <p className="public-kicker">Legal</p><h1 className="public-title mt-2 text-4xl md:text-5xl">Data Processing Addendum</h1>
    <p className="mt-3 text-xs text-[#4a4a4a]">Version {ORGANIZATION_AGREEMENT_VERSION} · Effective {ORGANIZATION_AGREEMENT_EFFECTIVE_DATE}</p>
    <p className="public-copy mt-4">This addendum applies when Coaches Hive processes personal data for an organization using the platform. Review the <a className="text-[#b80f0a] underline" href="/children-privacy">Children&apos;s Privacy Notice</a> for information about children under 13.</p>
    <div className="mt-8 space-y-5 text-sm leading-6 text-[#4a4a4a]">{items.map(([title, body], i) => <section key={title} className="glass-card rounded-2xl border border-[#191919] bg-white p-5"><h2 className="font-semibold text-[#191919]">{i + 1}. {title}</h2><p className="mt-2">{body}</p></section>)}</div>
  </div></main>
}
