'use client'

import { useEffect, useState } from 'react'

export default function OrgDiscoverySettings() {
  const [form,setForm]=useState({sport_primary:'',sports_additional:'',city:'',state:'',zip_code:''})
  const [message,setMessage]=useState('')
  useEffect(()=>{fetch('/api/org/discovery-profile').then(r=>r.json()).then(d=>d.profile&&setForm({sport_primary:d.profile.sport_primary||'',sports_additional:(d.profile.sports_additional||[]).join(', '),city:d.profile.city||'',state:d.profile.state||'',zip_code:d.profile.zip_code||''})).catch(()=>setMessage('Unable to load discovery profile.'))},[])
  const save=async()=>{setMessage('Saving…');const response=await fetch('/api/org/discovery-profile',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,sports_additional:form.sports_additional.split(',').map(v=>v.trim()).filter(Boolean)})});const data=await response.json().catch(()=>null);setMessage(response.ok?'Discovery profile saved.':data?.error||'Unable to save discovery profile.')}
  return <section className="glass-card border border-[#191919] bg-white p-6"><h2 className="text-lg font-semibold text-[#191919]">Discovery profile</h2><p className="mt-1 text-sm text-[#4a4a4a]">These canonical sport and location fields power athlete discovery on web and iOS.</p><div className="mt-4 grid gap-3 md:grid-cols-2"><input aria-label="Primary sport" placeholder="Primary sport" value={form.sport_primary} onChange={e=>setForm({...form,sport_primary:e.target.value})} className="rounded-2xl border border-[#dcdcdc] px-3 py-2"/><input aria-label="Additional sports" placeholder="Additional sports, comma separated" value={form.sports_additional} onChange={e=>setForm({...form,sports_additional:e.target.value})} className="rounded-2xl border border-[#dcdcdc] px-3 py-2"/><input aria-label="City" placeholder="City" value={form.city} onChange={e=>setForm({...form,city:e.target.value})} className="rounded-2xl border border-[#dcdcdc] px-3 py-2"/><div className="grid grid-cols-2 gap-3"><input aria-label="State" placeholder="State" maxLength={2} value={form.state} onChange={e=>setForm({...form,state:e.target.value})} className="rounded-2xl border border-[#dcdcdc] px-3 py-2 uppercase"/><input aria-label="ZIP code" placeholder="ZIP code" value={form.zip_code} onChange={e=>setForm({...form,zip_code:e.target.value})} className="rounded-2xl border border-[#dcdcdc] px-3 py-2"/></div></div><div className="mt-4 flex items-center gap-3"><button type="button" onClick={save} className="rounded-full bg-[#191919] px-5 py-2 text-sm font-semibold text-white">Save discovery profile</button>{message&&<span className="text-sm text-[#4a4a4a]">{message}</span>}</div></section>
}
