'use client'
import { useEffect, useState } from 'react'
import AdminSidebar from '@/components/AdminSidebar'

export default function GovernancePage() {
  const [snapshot,setSnapshot]=useState<Record<string,unknown>|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[retrying,setRetrying]=useState(false)
  const load=async()=>{setLoading(true);setError('');const response=await fetch('/api/admin/governance',{cache:'no-store'});const payload=await response.json().catch(()=>null);if(!response.ok)setError(payload?.error||'Unable to load governance.');else setSnapshot(payload?.snapshot||{});setLoading(false)}
  useEffect(()=>{void load()},[])
  const retry=async()=>{if(!window.confirm('Retry eligible failed Slack operational events?'))return;setRetrying(true);const response=await fetch('/api/admin/governance',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'retry_slack_events',confirmed:true})});const payload=await response.json().catch(()=>null);if(!response.ok)setError(payload?.error||'Unable to retry Slack events.');else await load();setRetrying(false)}
  return <main className="page-shell"><div className="relative z-10 px-6 py-10"><div className="grid items-start gap-6 lg:grid-cols-[200px_minmax(0,1fr)]"><AdminSidebar/><div><header><p className="text-xs font-bold uppercase tracking-[.24em] text-[#b80f0a]">Superadmin</p><h1 className="mt-2 text-3xl font-bold">Platform Governance</h1><p className="mt-2 text-sm text-neutral-600">Authoritative league capacity, access, compliance, notification, and operational health.</p></header>{loading?<p className="mt-8">Loading governance…</p>:error?<div className="mt-8 rounded-2xl border border-[#b80f0a] bg-white p-5"><p>{error}</p><button onClick={load} className="mt-3 rounded-full bg-[#191919] px-4 py-2 text-white">Retry</button></div>:<><section className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{Object.entries(snapshot||{}).map(([key,value])=><div key={key} className="rounded-2xl border border-[#dcdcdc] bg-white p-5"><p className="text-xs font-semibold uppercase tracking-wide text-[#4a4a4a]">{key.replaceAll('_',' ')}</p><p className="mt-2 break-words text-2xl font-semibold">{typeof value==='object'?JSON.stringify(value):String(value??0)}</p></div>)}</section><button onClick={retry} disabled={retrying} className="mt-6 rounded-full bg-[#191919] px-5 py-3 font-semibold text-white disabled:opacity-60">{retrying?'Retrying…':'Retry failed Slack events'}</button></>}</div></div></div></main>
}
