'use client'

import Link from 'next/link'
import { useCallback, useEffect, useState } from 'react'

type Kind = 'registrations'|'dues'|'events'|'fundraising'|'facilities'
const endpoints:Record<Kind,string>={registrations:'/api/org/enrollment',dues:'/api/org/dues',events:'/api/org/payment-events',fundraising:'/api/org/fundraising',facilities:'/api/facilities'}
const labels:Record<Kind,string>={registrations:'Registration',dues:'Recurring dues',events:'Events',fundraising:'Fundraising',facilities:'Facilities'}
const cents=(d:string)=>Math.round(Number(d||0)*100)

export default function CollectionsPage(){
 const[kind,setKind]=useState<Kind>('registrations'),[rows,setRows]=useState<any[]>([]),[notice,setNotice]=useState(''),[saving,setSaving]=useState(false)
 const[form,setForm]=useState<Record<string,string>>({name:'',description:'',amount:'',starts_on:'',ends_on:'',frequency:'monthly',event_type:'tournament',deadline:'',address:'',hourly_rate:'',payment_deadline:''})
 const load=useCallback(async()=>{const r=await fetch(endpoints[kind]);const d=await r.json().catch(()=>({}));setRows(d.forms||d.schedules||d.events||d.campaigns||d.facilities||[])},[kind])
 useEffect(()=>{load()},[load])
 const submit=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);setNotice('');let body:any={}
  if(kind==='registrations')body={title:form.name,description:form.description,enrollment_fee_cents:cents(form.amount),early_bird_fee_cents:form.early?cents(form.early):null,early_bird_deadline:form.early_deadline||null,late_fee_cents:form.late?cents(form.late):null,late_fee_starts_at:form.late_starts||null}
  if(kind==='dues')body={title:form.name,amount_cents:cents(form.amount),frequency:form.frequency,starts_on:form.starts_on,ends_on:form.ends_on||null}
  if(kind==='events')body={name:form.name,event_type:form.event_type,total_cost_cents:cents(form.amount),starts_at:form.starts_on,payment_deadline:form.payment_deadline||null,player_ids:[]}
  if(kind==='fundraising')body={name:form.name,description:form.description,goal_amount_cents:cents(form.amount),deadline:form.deadline||null,suggested_amounts_cents:[2500,5000,10000]}
  if(kind==='facilities')body={name:form.name,description:form.description,address:form.address,spaces:form.hourly_rate?[{name:'Main space',hourly_rate_cents:cents(form.hourly_rate)}]:[]}
  const r=await fetch(endpoints[kind],{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));setSaving(false);if(!r.ok){setNotice(d.error||'Unable to create collection');return}setForm({...form,name:'',description:'',amount:''});setNotice(`${labels[kind]} created.`);load()}
 return <main className="mx-auto w-full max-w-7xl px-4 py-8 sm:px-6"><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-neutral-500">Payments core</p><h1 className="text-3xl font-bold text-neutral-950">Collections</h1><p className="mt-2 max-w-2xl text-sm text-neutral-600">Create and monitor every way your organization collects money. Stripe confirmation remains the payment authority.</p></div><Link href="/org/payments" className="rounded-xl border px-4 py-2 text-sm font-semibold">Payment dashboard</Link></div>
 <nav className="mt-6 flex gap-2 overflow-x-auto pb-2">{(Object.keys(labels) as Kind[]).map(x=><button key={x} onClick={()=>setKind(x)} className={`whitespace-nowrap rounded-full px-4 py-2 text-sm font-semibold ${kind===x?'bg-neutral-950 text-white':'border bg-white text-neutral-700'}`}>{labels[x]}</button>)}</nav>
 <div className="mt-6 grid gap-6 lg:grid-cols-[minmax(0,420px)_1fr]"><form onSubmit={submit} className="h-fit space-y-4 rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-lg font-bold">Create {labels[kind].toLowerCase()}</h2><Field label="Name" value={form.name} onChange={v=>setForm({...form,name:v})}/>{['registrations','fundraising','facilities'].includes(kind)&&<Field label="Description" value={form.description} onChange={v=>setForm({...form,description:v})}/>} {kind!=='facilities'&&<Field label={kind==='fundraising'?'Goal (USD)':kind==='events'?'Total cost (USD)':'Amount (USD)'} type="number" value={form.amount} onChange={v=>setForm({...form,amount:v})}/>} {kind==='registrations'&&<><Field label="Early-bird fee (USD)" type="number" value={form.early||''} onChange={v=>setForm({...form,early:v})}/><Field label="Early-bird deadline" type="datetime-local" value={form.early_deadline||''} onChange={v=>setForm({...form,early_deadline:v})}/><Field label="Late fee (USD)" type="number" value={form.late||''} onChange={v=>setForm({...form,late:v})}/></>} {kind==='dues'&&<><label className="block text-sm font-medium">Frequency<select value={form.frequency} onChange={e=>setForm({...form,frequency:e.target.value})} className="mt-1 w-full rounded-xl border px-3 py-2"><option>weekly</option><option>monthly</option><option>quarterly</option><option>annual</option></select></label><Field label="Starts on" type="date" value={form.starts_on} onChange={v=>setForm({...form,starts_on:v})}/><Field label="Optional end date" type="date" value={form.ends_on} onChange={v=>setForm({...form,ends_on:v})}/></>} {kind==='events'&&<><Field label="Starts at" type="datetime-local" value={form.starts_on} onChange={v=>setForm({...form,starts_on:v})}/><Field label="Payment deadline" type="datetime-local" value={form.payment_deadline} onChange={v=>setForm({...form,payment_deadline:v})}/></>} {kind==='fundraising'&&<Field label="Deadline" type="datetime-local" value={form.deadline} onChange={v=>setForm({...form,deadline:v})}/>} {kind==='facilities'&&<><Field label="Address" value={form.address} onChange={v=>setForm({...form,address:v})}/><Field label="Main-space hourly rate (USD)" type="number" value={form.hourly_rate} onChange={v=>setForm({...form,hourly_rate:v})}/></>}<button disabled={saving} className="w-full rounded-xl bg-neutral-950 px-4 py-3 font-semibold text-white disabled:opacity-50">{saving?'Creating…':'Create'}</button>{notice&&<p className="text-sm text-neutral-700">{notice}</p>}</form>
 <section className="rounded-2xl border bg-white p-5 shadow-sm"><h2 className="text-lg font-bold">{labels[kind]} overview</h2><div className="mt-4 space-y-3">{rows.length?rows.map(r=><article key={r.id} className="rounded-xl border p-4"><div className="flex flex-wrap items-start justify-between gap-2"><div><h3 className="font-semibold">{r.title||r.name}</h3><p className="text-sm text-neutral-500">{r.frequency||r.event_type||r.address||r.description||'Active collection'}</p></div><span className="rounded-full bg-neutral-100 px-3 py-1 text-xs">{r.status||((r.active??r.is_active)?'active':'inactive')}</span></div>{r.slug&&<Link className="mt-3 inline-block text-sm font-semibold underline" href={kind==='registrations'?`/enroll/${r.slug}`:`/pay/${r.slug}`}>Open share page</Link>}</article>):<p className="rounded-xl bg-neutral-50 p-5 text-sm text-neutral-500">No {labels[kind].toLowerCase()} records yet.</p>}</div></section></div>
 <section className="mt-6 rounded-2xl border border-dashed p-5"><h2 className="font-bold">Future payment categories</h2><p className="mt-1 text-sm text-neutral-600">Equipment, travel, and insurance/compliance remain reserved in the unified ledger. Checkout is intentionally unavailable until their product rules are finalized.</p></section></main>}

function Field({label,value,onChange,type='text'}:{label:string,value:string,onChange:(v:string)=>void,type?:string}){return <label className="block text-sm font-medium">{label}<input required={label==='Name'} type={type} step={type==='number'?'0.01':undefined} min={type==='number'?'0':undefined} value={value} onChange={e=>onChange(e.target.value)} className="mt-1 w-full rounded-xl border px-3 py-2"/></label>}
