'use client'
import { FormEvent,useCallback,useEffect,useMemo,useState } from 'react'
import { useParams } from 'next/navigation'
import LeagueNav from '@/components/LeagueNav'

const allowed=['clubs','divisions','teams','schedule','registrations','payments','documents','submissions','announcements','staff','seasons','audit']
const titles:Record<string,string>={clubs:'Clubs',divisions:'Divisions & programs',teams:'Teams',schedule:'Schedule, standings & results',registrations:'Registrations & enrollment',payments:'Payments & balances',documents:'Document requirements',submissions:'Compliance submissions',announcements:'Announcements',staff:'Staff roles & permissions',seasons:'Seasons',audit:'Activity history'}
const money=(value:unknown)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(value||0)/100)
const date=(value:unknown)=>value?new Date(String(value)).toLocaleString():'Not set'
const label=(value:unknown)=>String(value||'Not set').replaceAll('_',' ')
function rowView(resource:string,row:any){
  if(resource==='clubs')return [row.organization?.org_name||'Organization',`Status: ${label(row.status)}`,`Joined ${date(row.joined_at)}`]
  if(resource==='divisions')return [row.name,[row.age_group,row.competition_level].filter(Boolean).join(' · ')||'Division details pending','']
  if(resource==='teams')return [row.team?.name||'Team',row.organization?.org_name||'Organization',`Status: ${label(row.status)}`]
  if(resource==='schedule')return [`${row.home_team?.name||'Home team'} vs ${row.away_team?.name||'Away team'}`,`${date(row.starts_at)} · ${row.location||'Location pending'}`,row.status==='completed'?`${row.home_score}–${row.away_score}`:label(row.status)]
  if(resource==='registrations')return [row.athlete?.full_name||'Athlete',`${row.team?.name||'Team not assigned'} · ${row.organization?.org_name||'Organization not assigned'}`,`Status: ${label(row.status)}`]
  if(resource==='payments')return [row.athlete?.full_name||row.organization?.org_name||'Fee assignment',`${money(row.paid_cents)} paid of ${money(row.amount_cents)}`,`Due ${date(row.due_at)} · ${label(row.status)}`]
  if(resource==='documents')return [row.title||'Document request',`${label(row.document_type)} · ${label(row.target_type)}`,`Due ${date(row.due_at)}${row.is_required?' · Required':''}`]
  if(resource==='submissions')return [row.organization?.org_name||row.team?.name||'Submission',`Status: ${label(row.status)}`,`Submitted ${date(row.created_at)}`]
  if(resource==='announcements')return [row.title,row.body,`${label(row.audience)} · ${date(row.published_at)}`]
  if(resource==='staff')return [row.user?.full_name||'League staff member',label(row.role),`Status: ${label(row.status)}`]
  if(resource==='seasons')return [row.name,`${date(row.start_date)} – ${date(row.end_date)}`,`Registration: ${label(row.registration_status)}`]
  return [label(row.event_type),`${label(row.record_type)} · ${date(row.occurred_at)}`,'']
}
export default function LeagueSectionPage(){const section=String(useParams().section||''),resource=allowed.includes(section)?section:'', [context,setContext]=useState<any>(null),[rows,setRows]=useState<any[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[canManage,setCanManage]=useState(false),[notice,setNotice]=useState(''),[saving,setSaving]=useState(false)
  const load=useCallback(async()=>{if(!resource){setError('That league section does not exist.');setLoading(false);return}setLoading(true);setError('');const contextResponse=await fetch('/api/league/context',{cache:'no-store'}),contextPayload=await contextResponse.json().catch(()=>null);if(!contextResponse.ok||!contextPayload?.active){setError(contextPayload?.error||'No active league is available.');setLoading(false);return}setContext(contextPayload.active);const response=await fetch(`/api/league/data?resource=${resource}&league_id=${contextPayload.active.id}`,{cache:'no-store'}),payload=await response.json().catch(()=>null);if(!response.ok)setError(payload?.error||'Unable to load this section.');else{setRows(payload?.rows||[]);setCanManage(Boolean(payload?.can_manage))}setLoading(false)},[resource]);useEffect(()=>{void load()},[load]);const heading=useMemo(()=>titles[resource]||'League',[resource])
  const submitAction=async(event:FormEvent<HTMLFormElement>,action:string,success:string)=>{event.preventDefault();const form=event.currentTarget,values=Object.fromEntries(new FormData(form).entries());setSaving(true);setNotice('');const response=await fetch('/api/league/data',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,league_id:context.id,...values,is_active:values.is_active==='on',is_required:values.is_required==='on'})}),payload=await response.json().catch(()=>null);if(!response.ok)setNotice(payload?.error||'Unable to save this change.');else{setNotice(success);form.reset();await load()}setSaving(false)}
  const field='rounded-xl border border-[#dcdcdc] px-3 py-3'
  const manageForm=canManage&&resource==='announcements'?<form onSubmit={event=>submitAction(event,'publish_announcement','Announcement published.')} className="mt-6 grid gap-3 rounded-2xl border border-[#dcdcdc] bg-white p-5"><h2 className="font-semibold">New league announcement</h2><input name="title" required placeholder="Announcement title" className={field}/><textarea name="body" required placeholder="Write the announcement" className={`${field} min-h-28`}/><button disabled={saving} className="justify-self-start rounded-full bg-[#191919] px-5 py-3 font-semibold text-white">{saving?'Publishing…':'Publish announcement'}</button></form>
    :canManage&&resource==='divisions'?<form onSubmit={event=>submitAction(event,'create_division','Division created.')} className="mt-6 grid gap-3 rounded-2xl border border-[#dcdcdc] bg-white p-5 md:grid-cols-2"><h2 className="font-semibold md:col-span-2">Create a division or program</h2><input name="name" required placeholder="Division name" className={field}/><input name="age_group" placeholder="Age group" className={field}/><input name="competition_level" placeholder="Competition level" className={field}/><select name="season_id" className={field} defaultValue=""><option value="">No season assigned</option></select><button disabled={saving} className="justify-self-start rounded-full bg-[#191919] px-5 py-3 font-semibold text-white">{saving?'Creating…':'Create division'}</button></form>
    :canManage&&resource==='seasons'?<form onSubmit={event=>submitAction(event,'create_season','Season created.')} className="mt-6 grid gap-3 rounded-2xl border border-[#dcdcdc] bg-white p-5 md:grid-cols-2"><h2 className="font-semibold md:col-span-2">Create a season</h2><input name="name" required placeholder="Season name" className={field}/><select name="registration_status" className={field} defaultValue="closed"><option value="closed">Registration closed</option><option value="open">Registration open</option></select><label className="grid gap-1 text-sm">Start date<input name="start_date" type="date" className={field}/></label><label className="grid gap-1 text-sm">End date<input name="end_date" type="date" className={field}/></label><label className="flex items-center gap-2 text-sm"><input name="is_active" type="checkbox"/> Make this the active season</label><button disabled={saving} className="justify-self-start rounded-full bg-[#191919] px-5 py-3 font-semibold text-white">{saving?'Creating…':'Create season'}</button></form>
    :canManage&&resource==='documents'?<form onSubmit={event=>submitAction(event,'create_document','Document requirement created.')} className="mt-6 grid gap-3 rounded-2xl border border-[#dcdcdc] bg-white p-5 md:grid-cols-2"><h2 className="font-semibold md:col-span-2">Create a document requirement</h2><input name="title" required placeholder="Document title" className={field}/><select name="target_type" className={field} defaultValue="organization"><option value="organization">Organizations</option><option value="team">Teams</option><option value="athlete">Athletes</option></select><input name="document_type" placeholder="Document type" className={field}/><label className="grid gap-1 text-sm">Due date<input name="due_at" type="date" className={field}/></label><label className="flex items-center gap-2 text-sm"><input name="is_required" type="checkbox" defaultChecked/> Required</label><button disabled={saving} className="justify-self-start rounded-full bg-[#191919] px-5 py-3 font-semibold text-white">{saving?'Creating…':'Create requirement'}</button></form>:null
  return <main className="page-shell min-h-screen"><div className="relative z-10 mx-auto max-w-7xl px-5 py-10"><div className="grid gap-6 lg:grid-cols-[220px_minmax(0,1fr)]"><LeagueNav/><div className="min-w-0"><p className="public-kicker">{context?.name||'League Director Portal'}</p><h1 className="mt-2 text-3xl font-semibold">{heading}</h1>{manageForm}{notice?<p role="status" className="mt-3 rounded-xl bg-white px-4 py-3 text-sm">{notice}</p>:null}{loading?<p className="mt-8">Loading {heading.toLowerCase()}…</p>:error?<div className="mt-8 rounded-2xl border border-[#b80f0a] bg-white p-5"><p>{error}</p><button onClick={load} className="mt-3 rounded-full bg-[#191919] px-4 py-2 text-white">Retry</button></div>:rows.length?<div className="mt-6 space-y-3">{rows.map((row)=>{const values=rowView(resource,row);return <article key={row.id} className="rounded-2xl border border-[#dcdcdc] bg-white p-5"><h2 className="font-semibold">{values[0]}</h2><p className="mt-1 whitespace-pre-wrap text-sm text-[#4a4a4a]">{values[1]}</p>{values[2]?<p className="mt-2 text-xs font-semibold capitalize text-[#4a4a4a]">{values[2]}</p>:null}{resource==='schedule'&&canManage?<form onSubmit={event=>submitAction(event,'submit_score','Score saved.')} className="mt-4 flex flex-wrap items-end gap-2"><input type="hidden" name="game_id" value={row.id}/><label className="grid gap-1 text-xs">Home score<input name="home_score" type="number" min="0" required defaultValue={row.home_score??''} className="w-24 rounded-lg border px-2 py-2"/></label><label className="grid gap-1 text-xs">Away score<input name="away_score" type="number" min="0" required defaultValue={row.away_score??''} className="w-24 rounded-lg border px-2 py-2"/></label><button disabled={saving} className="rounded-full bg-[#191919] px-4 py-2 text-sm font-semibold text-white">Save score</button></form>:null}</article>})}</div>:<div className="mt-8 rounded-2xl border border-[#dcdcdc] bg-white p-6"><h2 className="font-semibold">No {heading.toLowerCase()} yet</h2><p className="mt-2 text-sm text-[#4a4a4a]">New authorized records will appear here when they are available.</p></div>}</div></div></div></main>}
