'use client'

import { useCallback, useEffect, useState } from 'react'
import OrgSidebar from '@/components/OrgSidebar'
import LoadingState from '@/components/LoadingState'
import { createSafeClientComponentClient as createClient } from '@/lib/supabaseHelpers'
import { getActiveOrganizationId } from '@/lib/clientOrganization'
import { organizationWorkspaceHeaders } from '@/lib/clientWorkspaceRequest'

type RequestRow={id:string;status:string;request_note:string|null;decision_note:string|null;created_at:string;athlete_profiles:{full_name?:string|null}|Array<{full_name?:string|null}>|null;preflight:{team_assignments:number;unpaid_balances:number;active_recurring_billing:number;future_registrations:number;can_approve:boolean}|null}

export default function MemberRequestsPage(){
 const supabase=createClient(),[orgId,setOrgId]=useState<string|null>(null),[rows,setRows]=useState<RequestRow[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[notice,setNotice]=useState('')
 const auth=useCallback(async()=>{const id=orgId||await getActiveOrganizationId(supabase);if(!id)throw new Error('Organization workspace is unavailable.');if(!orgId)setOrgId(id);return{id,headers:await organizationWorkspaceHeaders(supabase,id)}},[orgId,supabase])
 const load=useCallback(async()=>{setLoading(true);setNotice('');try{const{id,headers}=await auth(),response=await fetch(`/api/mobile/organizations/${id}/leave-requests`,{headers,cache:'no-store'}),payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.message||payload.error||'Unable to load member requests.');setRows(payload.requests||[])}catch(error){setNotice(error instanceof Error?error.message:'Unable to load member requests.')}finally{setLoading(false)}},[auth])
 useEffect(()=>{void load()},[load])
 const resolve=async(row:RequestRow,decision:'approve'|'decline')=>{const note=window.prompt(decision==='approve'?'Optional approval note':'Why is this request being declined?','');if(note===null)return;setBusy(row.id);setNotice('');try{const{id,headers}=await auth(),response=await fetch(`/api/mobile/organizations/${id}/leave-requests/${row.id}/resolve`,{method:'POST',headers:{'Content-Type':'application/json',...headers},body:JSON.stringify({decision,note})}),payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.message||payload.error||'Unable to resolve request.');setNotice(`Request ${decision==='approve'?'approved':'declined'}.`);await load()}catch(error){setNotice(error instanceof Error?error.message:'Unable to resolve request.')}finally{setBusy('')}}
 return <div className="min-h-screen bg-[#f7f7f5]"><OrgSidebar/><main className="mx-auto max-w-5xl px-5 py-10 lg:pl-72"><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#b80f0a]">Membership operations</p><h1 className="mt-1 text-3xl font-bold">Leave requests</h1><p className="mt-2 text-gray-600">Review athlete requests without bypassing balances, recurring billing, or future registrations.</p>{notice&&<p role="status" className="mt-4 rounded-xl border bg-white p-3 text-sm">{notice}</p>}{loading?<LoadingState label="Loading leave requests…"/>:<div className="mt-6 space-y-4">{rows.map(row=>{const profile=Array.isArray(row.athlete_profiles)?row.athlete_profiles[0]:row.athlete_profiles,preflight=row.preflight;return <article key={row.id} className="rounded-2xl border bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-semibold">{profile?.full_name||'Athlete'}</h2><p className="text-sm text-gray-600">Requested {new Date(row.created_at).toLocaleString()} · {row.status}</p>{row.request_note&&<p className="mt-2 text-sm">{row.request_note}</p>}</div>{row.status==='pending'&&<div className="flex gap-2"><button disabled={busy===row.id||!preflight?.can_approve} onClick={()=>void resolve(row,'approve')} className="rounded-lg bg-[#191919] px-4 py-2 text-sm font-semibold text-white disabled:opacity-40">Approve</button><button disabled={busy===row.id} onClick={()=>void resolve(row,'decline')} className="rounded-lg border px-4 py-2 text-sm font-semibold disabled:opacity-40">Decline</button></div>}</div>{preflight&&<div className="mt-4 grid gap-2 text-sm sm:grid-cols-4"><Metric label="Unpaid balances" value={preflight.unpaid_balances}/><Metric label="Recurring billing" value={preflight.active_recurring_billing}/><Metric label="Future registrations" value={preflight.future_registrations}/><Metric label="Team assignments" value={preflight.team_assignments}/></div>}</article>})}{!rows.length&&<p className="rounded-2xl border bg-white p-8 text-center text-gray-500">No leave requests.</p>}</div>}</main></div>}

function Metric({label,value}:{label:string;value:number}){return <div className="rounded-xl bg-gray-50 p-3"><p className="text-xs text-gray-500">{label}</p><strong>{value}</strong></div>}
