import {NextResponse}from'next/server'
import {getMobileRequestUser}from'@/lib/mobileRequestAuth'
import {mobileContractError}from'@/lib/mobileApiContract'
import {supabaseAdmin}from'@/lib/supabaseAdmin'
import {parseUuid}from'@/lib/uuid'
const decode=(value:string|null)=>{if(!value)return null;try{const row=JSON.parse(Buffer.from(value,'base64url').toString('utf8'));return typeof row.updated_at==='string'&&parseUuid(row.id)?row:null}catch{return null}}
const encode=(row:{updated_at:string;id:string})=>Buffer.from(JSON.stringify({updated_at:row.updated_at,id:row.id})).toString('base64url')
export async function GET(request:Request){const user=await getMobileRequestUser(request);if(!user)return mobileContractError('unauthorized','Authentication is required.',401);const url=new URL(request.url),limit=Math.min(50,Math.max(1,Number(url.searchParams.get('limit'))||25)),cursor=decode(url.searchParams.get('cursor'));if(url.searchParams.has('cursor')&&!cursor)return mobileContractError('thread_cursor_invalid','Refresh your conversations and try again.',422)
 const{data:members,error:memberError}=await(supabaseAdmin as any).from('thread_participants').select('thread_id,muted_at,pinned_at').eq('user_id',user.id);if(memberError)return mobileContractError('threads_unavailable','Conversations are temporarily unavailable.',503,true);const ids=(members||[]).map((r:any)=>r.thread_id);if(!ids.length)return NextResponse.json({threads:[],next_cursor:null});let query=(supabaseAdmin as any).from('threads').select('id,title,is_group,org_id,organization_id,organization_display_name,organization_profile_image_url,updated_at').in('id',ids).order('updated_at',{ascending:false}).order('id',{ascending:false}).limit(limit+1);if(cursor)query=query.or(`updated_at.lt.${cursor.updated_at},and(updated_at.eq.${cursor.updated_at},id.lt.${cursor.id})`);const{data,error}=await query;if(error)return mobileContractError('threads_unavailable','Conversations are temporarily unavailable.',503,true);const rows=data||[],more=rows.length>limit,selected=rows.slice(0,limit),orgIds=Array.from(new Set(selected.map((r:any)=>r.organization_id||r.org_id).filter(Boolean)));const[{data:orgs},{data:settings},{data:participants},{data:lastMessages}]=await Promise.all([orgIds.length?(supabaseAdmin as any).from('organizations').select('id,name').in('id',orgIds):Promise.resolve({data:[]}),orgIds.length?(supabaseAdmin as any).from('org_settings').select('org_id,profile_image_url').in('org_id',orgIds):Promise.resolve({data:[]}),(supabaseAdmin as any).from('thread_participants').select('thread_id,user_id,profiles(full_name,avatar_url)').in('thread_id',selected.map((r:any)=>r.id)).neq('user_id',user.id),(supabaseAdmin as any).from('messages').select('id,thread_id,content,body,created_at,sender_id').in('thread_id',selected.map((r:any)=>r.id)).order('created_at',{ascending:false})]);const orgMap=new Map<string,any>((orgs||[]).map((r:any)=>[r.id,r])),settingMap=new Map<string,any>((settings||[]).map((r:any)=>[r.org_id,r])),people=new Map<string,any>();for(const p of participants||[])if(!people.has(p.thread_id))people.set(p.thread_id,p);const last=new Map<string,any>();for(const m of lastMessages||[])if(!last.has(m.thread_id))last.set(m.thread_id,m)
 const incoming=(lastMessages||[]).filter((m:any)=>m.sender_id!==user.id),{data:receipts}=incoming.length?await(supabaseAdmin as any).from('mobile_message_receipts').select('message_id').eq('user_id',user.id).not('read_at','is',null).in('message_id',incoming.map((m:any)=>m.id)):({data:[]}),readIds=new Set((receipts||[]).map((r:any)=>r.message_id));const unread=new Map<string,number>();for(const m of incoming)if(!readIds.has(m.id))unread.set(m.thread_id,(unread.get(m.thread_id)||0)+1)
 const threads=selected.map((row:any)=>{const orgId=row.organization_id||row.org_id||null,org=orgId?orgMap.get(orgId):null,setting=orgId?settingMap.get(orgId):null,person=people.get(row.id),message=last.get(row.id);return{thread_id:row.id,title:row.title,is_group:Boolean(row.is_group),organization_id:orgId,display_name:org?.name||row.organization_display_name||person?.profiles?.full_name||row.title||'Conversation',profile_image_url:setting?.profile_image_url||row.organization_profile_image_url||person?.profiles?.avatar_url||null,updated_at:row.updated_at,unread_count:unread.get(row.id)||0,last_message:message?{message_id:message.id,preview:String(message.content||message.body||'').slice(0,160),sender_id:message.sender_id,created_at:message.created_at}:null}});const tail=selected.at(-1);return NextResponse.json({threads,next_cursor:more&&tail?encode(tail):null},{headers:{'Cache-Control':'private, no-store'}})}
