import{NextResponse}from'next/server'
import{getMobileRequestUser}from'@/lib/mobileRequestAuth'
import{mobileContractError}from'@/lib/mobileApiContract'
import{supabaseAdmin}from'@/lib/supabaseAdmin'
import{parseUuid}from'@/lib/uuid'
import{canonicalUserAvatarMap,preserveVersionedAvatar}from'@/lib/mobileAvatarIdentity'
const decode=(value:string|null)=>{if(!value)return null;try{const row=JSON.parse(Buffer.from(value,'base64url').toString('utf8'));return typeof row.updated_at==='string'&&parseUuid(row.id)?row:null}catch{return null}}
const encode=(row:{updated_at:string;id:string})=>Buffer.from(JSON.stringify({updated_at:row.updated_at,id:row.id})).toString('base64url')
export async function GET(request:Request){
 const user=await getMobileRequestUser(request);if(!user)return mobileContractError('unauthorized','Authentication is required.',401)
 const url=new URL(request.url),limit=Math.min(50,Math.max(1,Number(url.searchParams.get('limit'))||25)),cursor=decode(url.searchParams.get('cursor'));if(url.searchParams.has('cursor')&&!cursor)return mobileContractError('thread_cursor_invalid','Refresh your conversations and try again.',422)
 const{data:members,error:memberError}=await supabaseAdmin.from('thread_participants').select('thread_id,muted_at,pinned_at').eq('user_id',user.id);if(memberError)return mobileContractError('threads_unavailable','Conversations are temporarily unavailable.',503,true);const ids=(members||[]).map(row=>row.thread_id);if(!ids.length)return NextResponse.json({threads:[],next_cursor:null})
 let query=(supabaseAdmin as any).from('threads').select('id,title,is_group,org_id,organization_id,organization_display_name,organization_profile_image_url,league_id,updated_at').in('id',ids).order('updated_at',{ascending:false}).order('id',{ascending:false}).limit(limit+1);if(cursor)query=query.or(`updated_at.lt.${cursor.updated_at},and(updated_at.eq.${cursor.updated_at},id.lt.${cursor.id})`);const{data,error}=await query;if(error)return mobileContractError('threads_unavailable','Conversations are temporarily unavailable.',503,true)
 const rows=data||[],more=rows.length>limit,selected=rows.slice(0,limit),threadIds=selected.map((row:any)=>row.id),orgIds=Array.from(new Set<string>(selected.map((row:any)=>row.organization_id||row.org_id).filter(Boolean))),leagueIds=Array.from(new Set<string>(selected.map((row:any)=>row.league_id).filter(Boolean)))
 const[{data:orgs},{data:settings},{data:leagues},{data:participants},{data:lastMessages}]=await Promise.all([orgIds.length?supabaseAdmin.from('organizations').select('id,name').in('id',orgIds):Promise.resolve({data:[]}),orgIds.length?supabaseAdmin.from('org_settings').select('org_id,profile_image_url').in('org_id',orgIds):Promise.resolve({data:[]}),leagueIds.length?supabaseAdmin.from('leagues').select('id,name,profile_image_url').in('id',leagueIds):Promise.resolve({data:[]}),(supabaseAdmin as any).from('thread_participants').select('thread_id,user_id,role,profiles(full_name,avatar_url)').in('thread_id',threadIds).neq('user_id',user.id),supabaseAdmin.from('messages').select('id,thread_id,content,body,created_at,sender_id').in('thread_id',threadIds).order('created_at',{ascending:false})])
 const avatarMap=await canonicalUserAvatarMap((participants||[]).map((row:any)=>row.user_id)),orgMap=new Map((orgs||[]).map(row=>[row.id,row])),settingMap=new Map((settings||[]).map(row=>[row.org_id,row])),leagueMap=new Map((leagues||[]).map(row=>[row.id,row])),people=new Map<string,any>();for(const participant of participants||[])if(!people.has(participant.thread_id))people.set(participant.thread_id,participant);const last=new Map<string,any>();for(const message of lastMessages||[])if(!last.has(message.thread_id))last.set(message.thread_id,message)
 const incoming=(lastMessages||[]).filter(message=>message.sender_id!==user.id),{data:receipts}=incoming.length?await supabaseAdmin.from('mobile_message_receipts').select('message_id').eq('user_id',user.id).not('read_at','is',null).in('message_id',incoming.map(message=>message.id)):{data:[]},readIds=new Set((receipts||[]).map(row=>row.message_id)),unread=new Map<string,number>();for(const message of incoming)if(!readIds.has(message.id))unread.set(message.thread_id,(unread.get(message.thread_id)||0)+1)
 const threads=selected.map((row:any)=>{const storedOrgId=row.organization_id||row.org_id||null,person=people.get(row.id),personToPerson=!row.is_group&&person&&!['organization','organization_contact'].includes(String(person.role||'')),orgId=personToPerson?null:storedOrgId,org=orgId?orgMap.get(orgId):null,setting=orgId?settingMap.get(orgId):null,league=row.league_id?leagueMap.get(row.league_id):null,profile=Array.isArray(person?.profiles)?person.profiles[0]:person?.profiles,message=last.get(row.id),identityAvatar=setting?.profile_image_url||(!personToPerson?row.organization_profile_image_url:null)||league?.profile_image_url||avatarMap.get(person?.user_id)||profile?.avatar_url;return{thread_id:row.id,title:row.title,is_group:Boolean(row.is_group),organization_id:orgId,league_id:row.league_id||null,display_name:org?.name||league?.name||(!personToPerson?row.organization_display_name:null)||profile?.full_name||row.title||'Conversation',profile_image_url:preserveVersionedAvatar(identityAvatar),updated_at:row.updated_at,unread_count:unread.get(row.id)||0,last_message:message?{message_id:message.id,preview:String(message.content||message.body||'').slice(0,160),sender_id:message.sender_id,created_at:message.created_at}:null}})
 const tail=selected.at(-1);return NextResponse.json({threads,next_cursor:more&&tail?encode(tail):null},{headers:{'Cache-Control':'private, no-store'}})
}
